    { (sbyte *)"test-cipher",           11, 16, 16, &TestSuite,         NULL },
    { (sbyte *)"test-cipher",           11, 32, 16, &TestSuite,         NULL },
    { (sbyte *)"test-cipher",           11, 24, 16, &TestSuite,         NULL },
    { (sbyte *)"test-cipher",           11, 16,  8, &TestSuite,         NULL },
    { (sbyte *)"test-cipher",           11, 24,  8, &TestSuite,         NULL },

