###########################################################
## PKCS11 Provisioning Configuration                     ##
## Used with pkcs11_provision_linux.sh script            ##
###########################################################
# AUTH: PKCS11 auth value
#   - softhsm2: Pin value specified when creating slot (ex: AUTH=0000)
#   - ssm: Not required for ssm. Auth values are picked up from environment
AUTH=0000
