: file: nanocert/build.bat
::
:: Summary:
::  BAT file to build nanocert.lib on windows.
::  Capable of building the static lib file using CMAKE and NMAKE
::
:: Pre-Requisites:
::  CMAKE
::  NMAKE (Bundled with Visual Studio installation)
::
:: Usage:
::  build.bat --debug --remote --log <log_file_path>
:: Arguments:
::  --debug: build with Debug version and logs enabled.
::  --remote: build with tap remote flag enabled.
::  --log: file path to ouput standard and error messages generated by this bat.

@echo OFF
SETLOCAL ENABLEEXTENSIONS
SETLOCAL ENABLEDELAYEDEXPANSION

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: -- Variables -- Modify the values as appropriate here

::Platform
set VS_PLATFORM=x64

::Out dir
set BUILD_DIR=build

set CopyBAT=..\..\scripts\win32\copy_build_to_bin.bat

::NMAKE paths
set NMAKE_PATH=
set NMAKE_BIN=nmake.exe
IF NOT [%NMAKE_PATH%]==[] (
    set NMAKE_BIN="%NMAKE_PATH%\nmake.exe"
)

::Log file path
set LOG_FILE="build_bat.out"

::VERBOSE_MODE - Set this variable to non-zero in order to print verbose messages, else set it to 0.
set VERBOSE_MODE=1

set LIB_NAME=nanocert
set LIB_TYPE=shared
::"x86" / "x64"
set TARGET_PLATFORM=x64
:: "Release" / "Debug"
set TARGET_CONFIG=Release
set LIBEXT=dll

::WIN_BUILD_MODE values - VSIDE is for building VisualStudio generator, and NMAKE for nmake generator
set WIN_BUILD_MODE=VSIDE

:: Check if VSINSTALLDIR is set (Visual Studio environment required)
if not defined VSINSTALLDIR (
    echo ERROR: VSINSTALLDIR is not set. Visual Studio build environment is required.
    echo Please run this script from a Visual Studio Developer Command Prompt or use vsdevcmd.bat
    exit /b 1
)

:: Detect VS version using string substitution (most reliable method)
set "VS_PATH=%VSINSTALLDIR%"

:: Check for VS 2026 (path contains \18\)
if not "!VS_PATH:\18\=!"=="!VS_PATH!" (
    echo Detected Visual Studio 2026
    set VSIDE_GENERATOR_x64="Visual Studio 18 2026" -A x64
    set VSIDE_GENERATOR_x32="Visual Studio 18 2026" -A Win32
    goto :VS_DETECTED
)

:: Check for VS 2022 (path contains \2022\)
if not "!VS_PATH:\2022\=!"=="!VS_PATH!" (
    echo Detected Visual Studio 2022
    set VSIDE_GENERATOR_x64="Visual Studio 17 2022" -A x64
    set VSIDE_GENERATOR_x32="Visual Studio 17 2022" -A Win32
    goto :VS_DETECTED
)

:: Check for VS 2019 (path contains \2019\)
if not "!VS_PATH:\2019\=!"=="!VS_PATH!" (
    echo Detected Visual Studio 2019
    set VSIDE_GENERATOR_x64="Visual Studio 16 2019" -A x64
    set VSIDE_GENERATOR_x32="Visual Studio 16 2019" -A Win32
    goto :VS_DETECTED
)

:: If we get here, VSINSTALLDIR is set but version is unknown
echo ERROR: Unsupported Visual Studio version. VSINSTALLDIR=%VSINSTALLDIR%
echo Supported versions: Visual Studio 2019, 2022, 2026
exit /b 1

:VS_DETECTED
:: Set CMAKE path based on VSINSTALLDIR
set "CMAKE_PATH=%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin"
set CMAKE_BIN="!CMAKE_PATH!\cmake.exe"

:: Check if CMAKE binary exists at the VS path
if exist "!CMAKE_PATH!\cmake.exe" (
    echo Using CMake from Visual Studio: !CMAKE_BIN!
    goto :CMAKE_READY
)

:: CMAKE not found in VS, check if it's in PATH
where cmake >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo CMake not found in Visual Studio installation, using cmake from PATH
    set CMAKE_BIN=cmake.exe
    goto :CMAKE_READY
)

:: CMAKE not found anywhere
echo ERROR: CMake is required but not found.
echo CMake was not found in Visual Studio installation at: !CMAKE_PATH!
echo CMake is also not available in PATH.
echo Please install CMake or use a Visual Studio installation that includes CMake.
exit /b 1

:CMAKE_READY

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Execution begins here.

set BAT_DIR=%~dp0
::set "BUILD_OPTIONS=-DLIB_TYPE:STRING=STATIC"
set "BUILD_OPTIONS="
call:echoIfVerbose BAT_DIR: %BAT_DIR%


GOTO:MAIN


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: end() - call this to exit from the script

:end
endlocal
if %ERRORLEVEL% NEQ 0 (echo.&echo Failure^(%errorlevel%^) encountered!)
echo.&echo Exiting....
::echo.&pause&exit /b %1
echo.&exit /b %ERRORLEVEL%


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: printLogOnFailure() - call this to print log file contents when VERBOSE_BUILD_LOG is set
:: Usage: call :printLogOnFailure "path\to\logfile.log"
:: Note: Prints last 200 lines to avoid GitHub Actions truncation

:printLogOnFailure
if defined VERBOSE_BUILD_LOG (
    if "%VERBOSE_BUILD_LOG%"=="1" (
        echo.
        echo ================================================================================
        echo BUILD LOG - ERRORS AND WARNINGS SUMMARY
        echo ================================================================================
        if exist "%~1" (
            findstr /i /c:"error" /c:"fatal" /c:"failed" "%~1" 2>nul
        )
        echo.
        echo ================================================================================
        echo BUILD LOG - LAST 200 LINES - %~1
        echo ================================================================================
        if exist "%~1" (
            powershell -NoProfile -Command "Get-Content '%~1' -Tail 200"
        ) else (
            echo Log file not found: %~1
        )
        echo ================================================================================
        echo END OF BUILD LOG
        echo ================================================================================
        echo.
    )
)
goto:EOF


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: echoIfVerbose() - call this to echo a statement needed only in verbose mode

:echoIfVerbose
IF %VERBOSE_MODE% NEQ 0 (
    echo %*
)
goto:EOF


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: parseArguments() - parses arguments to bat file

:parseArguments
    :parseArgumentsLoop
        IF "%~1"=="" GOTO parseArgumentsLoopEnd

        IF "%~1"=="--gdb" (
            echo Enabling Debug build...
            set TARGET_CONFIG=Debug
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCMAKE_BUILD_TYPE=Debug"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--pg" (
            echo Enabling callstack tracing build...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_PG=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--debug" (
            set TARGET_CONFIG=Debug
            echo Building debug build with with debug logs enabled...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_DEBUG=ON -DCMAKE_BUILD_TYPE=Debug"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--release" (
            set TARGET_CONFIG=Release
            echo Building Release build without debug logs ...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCMAKE_BUILD_TYPE=Release "
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--export" (
            echo Building Export Edition library...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_EXPORT_ED=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--forcelink" (
            echo Setting flags to force linkage ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_WIN_FORCE_LINKAGE=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--scep" (
            echo Building SCEP ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_SCEP=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--est" (
            echo Building EST ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_EST=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cms" (
            echo Building CMS ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_CMS=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cmc" (
            echo Building CMC ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_CMC=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--ocsp" (
            echo Building OCSP ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_OCSP=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--ocsp_cert" (
            echo Building with OCSP cert ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_OCSP_CERT=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--rsa_8k" (
            echo Building with RSA 8K support ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_RSA_8K=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--aide" (
            echo Building AIDE ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_AIDE=ON -DCM_ENABLE_CMS=ON -DCM_ENABLE_CMC=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cert" (
            echo Building with certificate search support...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_CERT=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--data-protect" (
            echo Building with data protect support...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_DATA_PROTECT=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--oqs" (
            echo PQC is enabled by default. Ignoring legacy --oqs flag.
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable-pqc" (
            echo "Building with PQC disabled..."
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_DISABLE_PQC=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--fips" (
            echo Linking to libmss...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_FIPS=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--x64" (
            set IS_64BIT_BUILD=1
            set TARGET_PLATFORM=x64
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--x32" (
            set IS_32BIT_BUILD=1
            set TARGET_PLATFORM=x32
            set VS_PLATFORM=Win32
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--log" (
            IF "%~2"=="" (
                echo "Error reading log file path %2"
                exit /b 1
            )
            set LOG_FILE="%~2"
            SHIFT & SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--libtype" (
            IF "%~2"=="static" (
                echo in static
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=STATIC"
                set LIB_TYPE=static
                set LIBEXT=lib
            ) ELSE IF "%~2"=="shared" (
                echo in shared
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=SHARED"
                set LIB_TYPE=shared
                set LIBEXT=dll
            ) ELSE (
                echo "Error reading libtype %2"
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=SHARED"
                set LIB_TYPE=shared
                set LIBEXT=dll
            )
            SHIFT & SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--suiteb" (
            echo "suiteb is enabled by default. Ignoring legacy --suiteb flag."
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable-suiteb" (
            echo "Building with suiteb disabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_DISABLE_SUITEB=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--tap" (
            echo Building with TAP Local...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_TAP=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--remote" (
            echo "Building with remote TAP configuration..."
            echo "Building with tap remote enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_TAP_REMOTE=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--openssl" (
            echo "Building with OpenSSL SHIM configuration..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_OPENSSL_SHIM=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--ssh" (
            echo "Building for SSH..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_SSH=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable-strict-ca-check" (
            echo "Disable strict CA check..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_DISABLE_STRICT_CA_CHECK=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable_cert_ext_check" (
            echo "Disable certificate extension check..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_DISABLE_CERT_EXT_CHECK=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--opts" (
             IF "%~2"=="" (
                echo "Error reading extra options from --otps: %2"
                exit /b 1
            )
            set "BUILD_OPTIONS=!BUILD_OPTIONS! %~2"
            SHIFT & SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cms" (
            echo "Building with CMS ..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_CMS=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--json-verify" (
            echo "Building with JSON sign and verify APIs ..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_JSON_VERIFY=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--status-log" (
            echo "Building with status logging..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_STATUS_LOG=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--proxy" (
            echo "Build with http proxy support"
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_PROXY=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cvc" (
            echo "Building with CV CERT ..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_CVC=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--enable-pc" (
            echo "Building with Certificate/CSR printing enabled."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_CERT_PRINT=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--ipv6" (
            echo "Building with IPV6 enabled ..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_IPV6=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--no-cryptointerface" (
            echo "Building with crypto interface disabled ..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_DISABLE_CI=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--cmake-opt" (
            echo "Setting extra flags for cmake execution..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! %~2"
            SHIFT
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--build-for-osi" (
            echo "Enabling BUILD_FOR_OSI..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DBUILD_FOR_OSI=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--pqc" (
            echo "PQC is enabled by default. Ignoring legacy --pqc flag."
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE (
            echo "Error: Invalid argument %1"
            exit /b 1
        )
    :parseArgumentsLoopEnd
exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: printLocalEnvs

:printLocalEnvs
    call:echoIfVerbose TARGET_CONFIG: %TARGET_CONFIG%
    call:echoIfVerbose LOG_FILE: %LOG_FILE%
    call:echoIfVerbose BUILD_OPTIONS: %BUILD_OPTIONS%
exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: build_nanocert

:build_nanocert
    call:echoIfVerbose %0:Starts
    set libNanocertFileName=%LIB_NAME%.%LIBEXT%
    echo Building "%libNanocertFileName%"
    ::pushd %BAT_DIR%

    if "%WIN_BUILD_MODE%"=="VSIDE" (
        echo ********** Building %LIB_NAME% library ********** >>!LOG_FILE!
        if !TARGET_PLATFORM!==x64 (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1 ...."
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        ) else (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1"
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        )

        call %CMAKE_BIN% --build . --config !TARGET_CONFIG! 1>>!LOG_FILE! 2>>&1

        if !ERRORLEVEL! NEQ 0 (
           set BUILD_ERR=!ERRORLEVEL!
           echo Build failed
           echo Exited with error !BUILD_ERR!
           echo Refer file "!LOG_FILE!" for details.
           call :printLogOnFailure "!LOG_FILE!"
           exit /b !BUILD_ERR!
        )
        echo "%LIB_NAME% library built successfully at !TARGET_CONFIG!\!libNanocertFileName!"
    ) else (
        echo Executing - "%CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1 ...."
        %CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if not exist "Makefile" (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo Executing - "%NMAKE_BIN% clean" ...
        %NMAKE_BIN% clean 1>>%LOG_FILE% 2>>&1

        echo Executing - "%NMAKE_BIN%" ...
        %NMAKE_BIN% 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: NMake Failed to build "!libNanocertFileName!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if NOT exist !libNanocertFileName! (
           echo Failure: NMake Failed to build "!libNanocertFileName!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo "%LIB_NAME% library built successfully at !libNanocertFileName!"
    )
    ::popd
    call:echoIfVerbose %0:Ends
exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Function to copy build target to bin dir
:copyToBin
    set src_dir=.
    if "%WIN_BUILD_MODE%"=="VSIDE" (
        set src_dir=%TARGET_CONFIG%
    )
    echo Executing copy bat - %CopyBAT% --srcDir=!src_dir! --linkType=%LIB_TYPE% --binName=%LIB_NAME% --binType=lib
    call %CopyBAT% --srcDir=!src_dir! --linkType=%LIB_TYPE% --binName=%LIB_NAME% --binType=lib
    echo Finished execution of copy bat
EXIT /B %ERRORLEVEL%


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: MAIN() - main entry point, called first

:MAIN

echo Received arguments: "%*"

::Parse arguments
call:parseArguments %* & IF ERRORLEVEL 1 goto:end %errorlevel%
call:printLocalEnvs

::Clean directories
call clean.bat 1>NUL 2>&1

echo ********** Building CryptoInterface library ********** >>%LOG_FILE%
call:build_nanocert & IF ERRORLEVEL 1 goto:end %errorlevel%

call:copyToBin & IF ERRORLEVEL 1 goto:end %errorlevel%

GOTO:end 0

