# Set the name of target binary
CONFIG_KERNEL_BIN_NAME="trustedge"
CONFIG_DEBUG=n
CONFIG_SIZE_OPTIMIZATIONS_AGGRESSIVE=y

# the number of bytes in the arena for C library malloc
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=1048576

CONFIG_REQUIRES_FULL_LIBC=y

# number of bytes for k_malloc
CONFIG_HEAP_MEM_POOL_SIZE=1048576

# Networking config
CONFIG_NET_SOCKETS=y
CONFIG_NETWORKING=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_POSIX_SEMAPHORES=y
CONFIG_POSIX_AEP_CHOICE_PSE51=y
CONFIG_POSIX_MESSAGE_PASSING=y
CONFIG_POSIX_NETWORKING=y
CONFIG_POSIX_SIGNALS=y
CONFIG_POSIX_REALTIME_SIGNALS=y
CONFIG_POSIX_API=y
CONFIG_REBOOT=y

# for enabling poxis threads
CONFIG_POSIX_THREADS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_DYNAMIC_THREAD=y

CONFIG_DYNAMIC_THREAD_POOL_SIZE=20
CONFIG_POSIX_THREAD_KEYS_MAX=20
CONFIG_POSIX_THREAD_THREADS_MAX=20
CONFIG_MAX_PTHREAD_MUTEX_COUNT=20
CONFIG_MAX_PTHREAD_COND_COUNT=20

# Enable thread awareness for debugging tools supporting it
CONFIG_DEBUG_THREAD_INFO=y

CONFIG_LOG=y

CONFIG_FLASH=y

CONFIG_SHELL=y
CONFIG_SHELL_LOG_LEVEL_INF=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y

CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FLASH_MAP=y

# Networking config
CONFIG_NET_IPV4=y
CONFIG_NET_IF_MAX_IPV4_COUNT=2
CONFIG_NET_IF_MAX_IPV6_COUNT=2
CONFIG_NET_TCP=y
CONFIG_NET_LOG=y

CONFIG_INIT_STACKS=y
# Network address config

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="10.1.2.3"
CONFIG_ETH_NATIVE_POSIX=n
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y

CONFIG_DNS_RESOLVER=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_SERVER1="8.8.8.8"

CONFIG_HWINFO=y

CONFIG_MAIN_STACK_SIZE=4096

# RSA_setPublicKeyData had RSA_N optimized out
CONFIG_NO_OPTIMIZATIONS=y

# Set current time from ntp server
CONFIG_SNTP=y
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_SNTP_INIT_RESYNC=y
CONFIG_POSIX_TIMERS=y
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="north-america.pool.ntp.org"

# Assign a static MAC to device
CONFIG_ETH_NATIVE_POSIX_MAC_ADDR="00:11:22:33:44:55"
CONFIG_ETH_NATIVE_POSIX=y
CONFIG_ETH_DRIVER=y
CONFIG_ETH_NATIVE_POSIX_RANDOM_MAC=n
