CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="bootloader/mcuboot/root-rsa-2048.pem"

# CONFIG_IMG_MANAGER depends on this
CONFIG_STREAM_FLASH=y

# CONFIG_MCUBOOT_IMG_MANAGER depends on this, already set above
CONFIG_FLASH_MAP=y

# required for including <zephyr/dfu/mcuboot.h>
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y

CONFIG_IMG_BLOCK_BUF_SIZE=32

CONFIG_IMG_ENABLE_IMAGE_CHECK=y
#CONFIG_IMG_ENABLE_IMAGE_CHECK=y
CONFIG_MCUBOOT_UTIL_LOG_LEVEL_DBG=y
#CONFIG_IMG_MANAGER=y
