# the number of bytes in the arena for C library malloc
#CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=20000

# heap and stack tracking requires additional file handles
CONFIG_HEAP_MEM_POOL_SIZE=321000
