/*
 * e_moc_evp_err.h
 *
 * Copyright 2026 DigiCert Project Authors. All Rights Reserved.
 *
 * DigiCert® TrustCore and TrustEdge are licensed under a dual-license model:
 * - **Open Source License**: GNU AGPL v3. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE
 * - **Commercial License**: Available under DigiCert’s Master Services Agreement. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE_COMMERCIAL.txt
 *   or https://www.digicert.com/master-services-agreement/
 *
 * For commercial licensing, contact DigiCert at sales@digicert.com.*
 *
 */

/*
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#ifndef HEADER_MOC_EVP_ERR_H
# define HEADER_MOC_EVP_ERR_H

# ifdef  __cplusplus
extern "C" {
# endif

/* BEGIN ERROR CODES */
void ERR_load_DIGI_EVP_strings(void);
void ERR_unload_DIGI_EVP_strings(void);
void ERR_DIGI_EVP_error(int function, int reason, char *file, int line);
# define MOC_EVPerr(f,r) ERR_DIGI_EVP_error((f),(r),__FILE__,__LINE__)

/* Error codes for the AFALG functions. */

/* Function codes. */
# define MOC_EVP_F_BIND                               100

/* Reason codes. */
# define MOC_EVP_R_INIT_FAILED                              100
# define MOC_EVP_R_MEM_ALLOC_FAILED                         102

#ifdef  __cplusplus
}
#endif
#endif
