/**
 * @file tpm2_server_helpers.h
 * @brief This file includes helpers required on the server side of the
 * privacy CA protocol. A CA may use these helper functions to perform
 * wrapping of credentials etc without the need for a TPM.
 *
 * Copyright 2025 DigiCert Project Authors. All Rights Reserved.
 * 
 * DigiCert® TrustCore and TrustEdge are licensed under a dual-license model:
 * - **Open Source License**: GNU AGPL v3. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE
 * - **Commercial License**: Available under DigiCert’s Master Services Agreement. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE_COMMERCIAL.txt  
 *   or https://www.digicert.com/master-services-agreement/
 * 
 * *For commercial licensing, contact DigiCert at sales@digicert.com.*
 */
#ifndef __TPM2_SERVER_HELPERS_H__
#define __TPM2_SERVER_HELPERS_H__

#include "../../../../common/moptions.h"
#include "../../../../common/mtypes.h"
#include "../../../../common/merrors.h"
#include "../../../../common/mocana.h"
#include "../../../../common/mdefs.h"
#include "../../../../crypto/hw_accel.h"
#include "../../../../crypto/crypto.h"
#include "../../../../crypto/pubcrypto.h"
#include "../../../../crypto/pkcs1.h"
#include "../tpm2_types.h"

/*
 * This API can be used by a party who wishes to wrap a credential(such as
 * a certificate or a key that wraps a certificate) using the credential
 * protection mechanism defined in the TPM2.0 Library Specifications.
 * Once a credential is wrapped, it can only be unwrapped by the TPM that
 * has loaded both the Root of trust key(Typically the Endorsement Key of a TPM)
 * and the key with which the credential is being associated with(typically
 * an Attestation Key(AK or AIK).
 * With this protocol, the credential requester does not provide any proof of
 * possession of any private key. To use this API, DIGICERT_initDigicert() must have
 * been called.
 *
 * pAkPublicKey - This is an Asymmetrickey initialized with the public key
 * of the key, for which the credential is being provided. This is typically
 * an Attestation key. This function validates that the provided public key
 * is the same as the one in the base64 blob. Its TPM specific properties are
 * also validated. The code ensures that this key is a restricted signing key,
 * that is fixed to a TPM and whose private key was created inside the TPM.
 * This must be an RSA or ECC key.
 *
 * pRotPublicKey - This is an AsymmetricKey initialized with the public key
 * of a root of trust key, which is typically the endorsement key of a TPM.
 * However, It may be any restricted decryption(Storage Key) of a TPM. The
 * caller MUST have validated(through a certificate chain or some other means) that
 * this public key is a trusted key that belongs and resides in a TPM. This is CRITICAL
 * to the security of the protocol. IF this is always an endorsement key, a caller
 * may walk to the certificate chain for this key to the TPM manufacturer to be
 * guaranteed that the key belongs to a TPM.
 *
 * pBase64Blob - The base 64 blob containing the public area of pAkPublicKey.
 * The base 64 blob can be obtained by using Mocana NanoTAP or NanoSMP API's.
 * This blob contains the TPM specific attributes for the pAkPublicKey and
 * for the root of trust key(EK) of the TPM. These attributes are validated
 * to ensure that they are restricted signing and decryption keys, fixed to
 * a particular TPM, and whose private keys were generated inside the TPM.
 * See description of client side API for more information on what is wrapped
 * in this blob.
 *
 * blobLen - Length of the base64 blob.
 *
 * pDecryptKey - Pointer to a buffer that contains a key that is used to wrap the
 * credential(such as x509 certificate), generated by the caller. The intent
 * for this buffer is to be some sort of encryption key or seed that is used
 * to encrypt the credential(such as x509 certiticate) itself.
 * This key is then wrapped using the TPM2 credential protection protocol.
 * This key can only be recovered by the TPM to which
 * the key is wrapped to. This ensures that the credential can only be used
 * if this key is recovered. No checking is performed on the contents of this
 * buffer and the contents are protected as is.
 *
 * decryptKeyLen - length of buffer pointed by pDecryptKey.
 *
 * ppEncryptedDecryptKey - Buffer that contains the content of pDecryptKey
 * wrapped using the TPM2 credential protection protocol. This blob can be
 * fed into Mocana NanoTAP or NanoSMP API to recover pDecryptKey on the client side.
 * pDecryptKey can only be recovered if the TPM contains the private keys corresponding to
 * pAkPublicKey and pRoTPublicKey. Once pDecryptKey is recovered, the credential itself
 * can be unwrapped.
 *
 * pEncryptedDecryptKeyLen - pointer to a location where the length of the resulting
 * buffer is populated.
 */
MOC_EXTERN MSTATUS SMP_TPM2_wrapCredentialSecret(
        AsymmetricKey *pAkPublicKey,
        AsymmetricKey *pRoTPublicKey,
        ubyte *pBase64Blob,
        ubyte4 blobLen,
        ubyte *pDecryptKey,
        ubyte4 decryptKeyLen,
        ubyte **ppEncryptedDecryptKey,
        ubyte4 *pEncryptedDecryptKeyLen
);

#endif /* __TPM2_SERVER_HELPERS_H__ */
