: file: nanosec/build.bat
::
:: Summary:
::  BAT file to build nanosec.lib and nanosec target on windows.
::  Capable of building the static lib file using CMAKE and NMAKE
::
:: Pre-Requisites:
::  CMAKE
::  NMAKE (Bundled with Visual Studio installation)
::
:: Usage:
::  build.bat --dual-mode --debug --tap-local 
:: Arguments:
::	--dual-mode     Enable GEHC Dual mode
::  --debug: build with Debug version and logs enabled.
::  --remote: build with tap remote flag enabled.
::  --log: file path to ouput standard and error messages generated by this bat.

@echo OFF
SETLOCAL ENABLEEXTENSIONS
SETLOCAL ENABLEDELAYEDEXPANSION

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: -- Variables -- Modify the values as appropriate here

::Platform
set VS_PLATFORM=x64

::Out dir
set BUILD_DIR=build

set CopyBAT=..\..\scripts\win32\copy_build_to_bin.bat

::CMAKE paths
set CMAKE_PATH=C:\Program Files\CMake\bin
set CMAKE_BIN="%CMAKE_PATH%\cmake.exe"

::NMAKE paths
set NMAKE_PATH=
set NMAKE_BIN=nmake.exe
IF NOT [%NMAKE_PATH%]==[] (
    set NMAKE_BIN="%NMAKE_PATH%\nmake.exe"
)

::Log file path
set LOG_FILE="build_bat.out"

::VERBOSE_MODE - Set this variable to non-zero in order to print verbose messages, else set it to 0.
set VERBOSE_MODE=1

set LIB_NAME=nanosec
set TARGET_NAME=nanosec_target
set LIB_TYPE=shared
::"x86" / "x64"
set TARGET_PLATFORM=x64
:: "Release" / "Debug"
set TARGET_CONFIG=Release
set LIBEXT=dll
set TARGETEXT=exe
set APPEND_TARGET=target

::WIN_BUILD_MODE values - VSIDE is for building VisualStudio generator, and NMAKE for nmake generator
set WIN_BUILD_MODE=VSIDE
set VSIDE_GENERATOR_x64="Visual Studio 15 2017 Win64"
set VSIDE_GENERATOR_x32="Visual Studio 15 2017"

echo "%VSINSTALLDIR%" | findstr /C:"2019" 1>/NUL
if %ERRORLEVEL% EQU 0 (
    set VSIDE_GENERATOR_x64="Visual Studio 16 2019" -A x64
    set VSIDE_GENERATOR_x32="Visual Studio 16 2019" -A Win32
)

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Execution begins here.

set BAT_DIR=%~dp0
::set "BUILD_OPTIONS=-DLIB_TYPE:STRING=STATIC"
set "BUILD_OPTIONS="
set "ADD_ARGS="
set /A NO_TARGET=0
set /A EAPA=0
set /A EAPS=0
set /A TLS=0
set /A BUILD_TARGET=0
call:echoIfVerbose BAT_DIR: %BAT_DIR%


GOTO:MAIN


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: end() - call this to exit from the script

:end
endlocal
if ERRORLEVEL 1 (echo.&echo Failure^(%errorlevel%^) encountered!)
echo.&echo Exiting....
::echo.&pause&exit /b %1
echo.&exit /b %1


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: echoIfVerbose() - call this to echo a statement needed only in verbose mode

:echoIfVerbose
IF %VERBOSE_MODE% NEQ 0 (
    echo %*
)
goto:EOF


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: parseArguments() - parses arguments to bat file

:parseArguments
    :parseArgumentsLoop
        IF "%~1"=="" GOTO parseArgumentsLoopEnd

        IF "%~1"=="--gdb" (
            echo Enabling Debug build...
            set TARGET_CONFIG=Debug
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCMAKE_BUILD_TYPE=Debug"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--debug" (
            set TARGET_CONFIG=Debug
            echo Building debug build with with debug logs enabled...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_DEBUG=ON -DCMAKE_BUILD_TYPE=Debug"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--release" (
            set TARGET_CONFIG=Release
            echo Building Release build without debug logs ...
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCMAKE_BUILD_TYPE=Release "
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--example" (
            echo Building with example...
            set /A BUILD_TARGET=1
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_BUILD_EXAMPLE=ON"
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--forcelink" (
            echo Setting flags to force linkage ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_WIN_FORCE_LINKAGE=ON
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--eap-s" (
            echo Building with EAP supplicant ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_EAPS=ON
            set /A EAPS=1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--eap-a" (
            echo Building with EAP authenticator ...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_EAPA=ON
            set /A EAPA=1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--tls" (
            echo Building with TLS...
            ::set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_CMC=ON
            set /A TLS=1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--data-protect" (
            echo Building with Data Protect...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_DATA_PROTECTION=ON
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--trustedge" (
            echo Building with TrustEdge mode enabled...
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_TRUSTEDGE=ON
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--oqs" (
            echo "PQC is enabled by default. Ignoring legacy --oqs flag."
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="--pqc" (
            echo "PQC is enabled by default. Ignoring legacy --pqc flag."
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--suiteb" (
            echo "suiteb is enabled by default. Ignoring legacy --suiteb flag."
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable-suiteb" (
            echo "Building with suiteb disabled..."
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_DISABLE_SUITEB=ON
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--disable-pqc" (
            echo "Building with PQC disabled..."
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_DISABLE_PQC=ON
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="ike" (
            echo Building ike target..
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_BUILD_IKE=ON
            set ADD_ARGS=%ADD_ARGS%%1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="mcpagent" (
            echo Building mcpagent target..
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_BUILD_MCPA=ON
            set ADD_ARGS=%ADD_ARGS%%1
            set /A NO_TARGET = %NO_TARGET% + 1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="kdc" (
            echo Building kdc target..
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_BUILD_MCPK=ON
            set ADD_ARGS=%ADD_ARGS%%1
            set /A NO_TARGET = %NO_TARGET% + 1

            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF "%1"=="kdc_secondary" (
            echo Building kdc_secondary target..
            set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_BUILD_MCPK2=ON
            set ADD_ARGS=%ADD_ARGS%%1
            set /A NO_TARGET = %NO_TARGET% + 1
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF %1==--x64 (
            set IS_64BIT_BUILD=1
            set TARGET_PLATFORM=x64
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE IF %1==--x32 (
            set IS_32BIT_BUILD=1
            set TARGET_PLATFORM=x32
            set VS_PLATFORM=Win32
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--log" (
            IF "%~2"=="" (
                echo "Error reading log file path %2"
                exit /b 1
            )
            set LOG_FILE="%~2"
            SHIFT & SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--libtype" (
            IF "%~2"=="static" (
                echo in static
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=STATIC"
                set LIB_TYPE=static
                set LIBEXT=lib
            ) ELSE IF "%~2"=="shared" (
                echo in shared
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=SHARED"
                set LIB_TYPE=shared
                set LIBEXT=dll
            ) ELSE (
                echo "Error reading libtype %2"
                set "BUILD_OPTIONS=!BUILD_OPTIONS! -DLIB_TYPE:STRING=SHARED"
                set LIB_TYPE=shared
                set LIBEXT=dll
            )
            SHIFT & SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--nw-red" (
            echo "Building with nw redundancy enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_NW_RED=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--dual-mode" (
            echo "Building with dual-mode enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_DUAL_MODE=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--tap-local" (
            echo "Building with tap-local enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_TAP_LOCAL=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--tap-remote" (
            echo "Building with tap-remote enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_TAP_REMOTE=ON"
            SHIFT
            GOTO parseArgumentsLoop
        )
        if "%~1"=="--export" (
            echo "Building with export enabled..."
            set "BUILD_OPTIONS=!BUILD_OPTIONS! -DCM_ENABLE_EXPORT=ON"
            SHIFT
            GOTO parseArgumentsLoop
        ) ELSE (
            echo "Error: Invalid argument %1"
            exit /b 1
        )
		echo next counter: %BUILD_OPTIONS%
    :parseArgumentsLoopEnd
:: Check that a valid set of arguments were passed

	IF %EAPA%==1 IF %EAPS%==1 (echo "Can only build with either --eap-s or -eap-a."  exit /b 1)

	IF %NO_TARGET%==0 (echo "No target was provided. Max allowed: 1" exit /b 1)

	IF %NO_TARGET% GTR 1 (echo "Can only build one target at a time."	exit /b 1)

	IF %TLS%==1 (
		IF %EAPA%==1 (
			set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_TLSA=ON
			)
		ELSE (
			IF %EAPS%==1 (
				set BUILD_OPTIONS=%BUILD_OPTIONS% -DCM_ENABLE_TLSS=ON
				)
			ELSE (
				echo "TLS only works with EAP supplicant or authenticator builds"
				exit /b 1
			)
		)
	)
	set BUILD_TGT=%ADD_ARGS%

exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: printLocalEnvs

:printLocalEnvs
    call:echoIfVerbose TARGET_CONFIG: %TARGET_CONFIG%
    call:echoIfVerbose LOG_FILE: %LOG_FILE%

	call:echoIfVerbose LOG_FILE_TARGET: %LOG_FILE%
    call:echoIfVerbose BUILD_OPTIONS: %BUILD_OPTIONS%
exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: build_nanosec
:build_nanosec
    call:echoIfVerbose %0:Starts
    set libNanosecFileName=%LIB_NAME%.%LIBEXT%
    echo Building "%libNanosecFileName%"
    echo Building "%BUILD_TGT%"
    ::pushd %BAT_DIR%

    if "%WIN_BUILD_MODE%"=="VSIDE" (
        echo ********** Building %LIB_NAME% library ********** >>!LOG_FILE!
        if !TARGET_PLATFORM!==x64 (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DBUILD_TGT=%BUILD_TGT% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1 ...."
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DBUILD_TGT=%BUILD_TGT% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        ) else (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DBUILD_TGT=%BUILD_TGT% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1"
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DBUILD_TGT=%BUILD_TGT% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        )

        call msbuild %LIB_NAME%.sln /property:Configuration=!TARGET_CONFIG! /p:Platform=%VS_PLATFORM% 1>>!LOG_FILE! 2>>&1

        if !ERRORLEVEL! NEQ 0 (
           echo Build failed
           echo Exited with error !ERRORLEVEL!
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )
        echo "%LIB_NAME% library built successfully at !TARGET_CONFIG!\!libNanosecFileName!"
    ) else (
        echo Executing - "%CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1 ...."
        %CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if not exist "Makefile" (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo Executing - "%NMAKE_BIN% clean" ...
        %NMAKE_BIN% clean 1>>%LOG_FILE% 2>>&1

        echo Executing - "%NMAKE_BIN%" ...
        %NMAKE_BIN% 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: NMake Failed to build "!libNanosecFileName!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if NOT exist !libNanosecFileName! (
           echo Failure: NMake Failed to build "!libNanosecFileName!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo "%LIB_NAME% library built successfully at !libNanosecFileName!"
    )
    ::popd
    call:echoIfVerbose %0:Ends
exit /b 0


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Function to copy build target to bin dir
:copyToBin
    set src_dir=.
    if "%WIN_BUILD_MODE%"=="VSIDE" (
        set src_dir=%TARGET_CONFIG%
    )
    echo Executing copy bat - %CopyBAT% --srcDir=!src_dir! --linkType=%LIB_TYPE% --binName=%LIB_NAME% --binType=lib
    call %CopyBAT% --srcDir=!src_dir! --linkType=%LIB_TYPE% --binName=%LIB_NAME% --binType=lib
    echo Finished execution of copy bat
EXIT /B %ERRORLEVEL%


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: build_nanosec target
:build_nanosec_target
	::del /s /q %LOG_FILE%
    call:echoIfVerbose %0:Starts
    set libNanosecFileName=%TARGET_NAME%.%TARGETEXT%
    echo Building "%BUILD_TGT%"
    set BUILD_EXECUTABLE=%BUILD_TGT%_%APPEND_TARGET%
    ::pushd %BAT_DIR%

    ::echo 5build options is %BUILD_OPTIONS%
    if "%WIN_BUILD_MODE%"=="VSIDE" (
        echo ********** Building %TARGET_NAME%  ********** >>!LOG_FILE!
        if !TARGET_PLATFORM!==x64 (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DTARGET_PLATFORM=%TARGET_PLATFORM% -DLIB_TGT=%BUILD_TGT% -DBUILD_TGT=%BUILD_EXECUTABLE% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt \example\. 1>>!LOG_FILE! 2>>&1 ...."
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x64% -DTARGET_PLATFORM=%TARGET_PLATFORM% -DLIB_TGT=%BUILD_TGT% -DBUILD_TGT=%BUILD_EXECUTABLE% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! example\CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        ) else (
            echo Executing - "%CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DTARGET_PLATFORM=%TARGET_PLATFORM% -DLIB_TGT=%BUILD_TGT% -DBUILD_TGT=%BUILD_EXECUTABLE% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! CMakeLists.txt \example\. 1>>!LOG_FILE! 2>>&1"
            call %CMAKE_BIN% -G %VSIDE_GENERATOR_x32% -DTARGET_PLATFORM=%TARGET_PLATFORM% -DLIB_TGT=%BUILD_TGT% -DBUILD_TGT=%BUILD_EXECUTABLE% -DCMAKE_BUILD_TYPE=!TARGET_CONFIG! !BUILD_OPTIONS! example\CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        )

        call msbuild example\%TARGET_NAME%.sln /property:Configuration=!TARGET_CONFIG! /p:Platform=%VS_PLATFORM% 1>>!LOG_FILE! 2>>&1

        if !ERRORLEVEL! NEQ 0 (
           echo Build failed
           echo Exited with error !ERRORLEVEL!
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )
        echo "%TARGET_NAME% target built successfully at !TARGET_CONFIG!\!BUILD_EXECUTABLE!"
    ) else (
        echo Executing - "%CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! \CMakeLists.txt 1>>!LOG_FILE! 2>>&1 ...."
        %CMAKE_BIN% -G "NMake Makefiles" !BUILD_OPTIONS! example\CMakeLists.txt 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if not exist "Makefile" (
           echo Failure: CMake Failed to create Makefile
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo Executing - "%NMAKE_BIN% clean" ...
        %NMAKE_BIN% clean 1>>%LOG_FILE% 2>>&1

        echo Executing - "%NMAKE_BIN%" ...
        %NMAKE_BIN% 1>>!LOG_FILE! 2>>&1
        if !ERRORLEVEL! NEQ 0 (
           echo Failure: NMake Failed to build "!BUILD_EXECUTABLE!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b !ERRORLEVEL!
        )

        if NOT exist !BUILD_EXECUTABLE! (
           echo Failure: NMake Failed to build "!BUILD_EXECUTABLE!" from "Makefile"
           echo Refer file "!LOG_FILE!" for details.
           exit /b 2
        )

        echo "%TARGET_NAME% built successfully at !BUILD_EXECUTABLE!"
    )
	::popd
    call:echoIfVerbose %0:Ends
exit /b 0

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Function to copy build target to bin dir
:copyExcecutableToBin
    set src_dir=.
    set src_dir=..\..\bin_win32\
	cd ..\..\bin_win32\
	del %BUILD_TGT%.%TARGETEXT%
	echo renaming from "%BUILD_EXECUTABLE%.%TARGETEXT% %BUILD_TGT%.%TARGETEXT%"
	rename %BUILD_EXECUTABLE%.%TARGETEXT% %BUILD_TGT%.%TARGETEXT%
	set ERRORLEVEL=0
    echo Finished execution of copying executable to bin
EXIT /B %ERRORLEVEL%


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: MAIN() - main entry point, called first

:MAIN

echo Received arguments: "%*"

::Parse arguments
call:parseArguments %* & IF ERRORLEVEL 1 goto:end %errorlevel%
call:printLocalEnvs
IF %BUILD_TARGET%==0 (
	::Clean directories
	call clean.bat 1>NUL 2>&1
	echo ********** Building NanoSec library/Target ********** >>%LOG_FILE%
	call:build_nanosec & IF ERRORLEVEL 1 goto:end %errorlevel%

	call:copyToBin & IF ERRORLEVEL 1 goto:end %errorlevel%
) ELSE (
	:: build binary and copy it
	echo ********** Building NanoSec Target ********** >>%LOG_FILE%
	call:build_nanosec_target & IF ERRORLEVEL 1 goto:end %errorlevel%

	call:copyExcecutableToBin & IF ERRORLEVEL 1 goto:end %errorlevel%
)

GOTO:end 0

