##############################################
## TPM2 Provisioning Configuration          ##
## Used with tpm2_provision_linux.sh script ##
##############################################
# DEVICE: TPM2 Device (default: /dev/tpm0)
DEVICE=/dev/tpm0
# LH_PWD: Lockout Hierarchy (LH) password. If no password is specified, the well-known password is used.
LH_PWD=
# EH_PWD: Endorsement Hierarchy (EH) password. If no password is specified, the well-known password is used.
EH_PWD=
# SH_PWD: Storage Hierarchy (SH) password. If no password is specified, the well-known password is used.
SH_PWD=
# EK_PWD: Endorsement Key (EK) password. If no password is specified, the EH password is used.
EK_PWD=
# EK_ALGO: Algorithm (ecc or rsa) to create the EK.
EK_ALGO=rsa
# SRK_PWD: Storage Root Key (SRK) password. If no password is specified, the SH password is used.
SRK_PWD=
# SRK_ALGO: Algorithm (ecc or rsa) to create the SRK.
SRK_ALGO=rsa
# AUTH_FAIL: Number of authorization failues before lockout is imposed.
AUTH_FAIL=10
# RCY_TIME: Time in seconds before the count authorization failures is automatically decremented. A value of 0 indicates that DA protection is disabled.
RCY_TIME=300
# LORCY: Time in seconds after a lockout authentication failure before user of lockout authentication is allowed. A value of 0 indicates that a reboot is required.
LORCY=300
# CRED_FILE: TPM2 credentials file (default: creds.tpm2)
CRED_FILE=creds.tpm2
