/**
 * @file  eap_peap.c
 * @brief EAP-PEAP method implementation
 *
 * @details    Protected EAP
 * @since      1.41
 * @version    1.41 and later
 *
 * @flags      Compilation flags required:
 *     To enable any of this file's functions, the following flag must be defined in
 *     moptions.h:
 *     +   \c \__ENABLE_DIGICERT_EAP_PEAP__
 *     Additionally, at least one of the following flags must be defined in moptions.h:
 *     +   \c \__ENABLE_DIGICERT_EAP_AUTH__
 *     +   \c \__ENABLE_DIGICERT_EAP_PEER__
 *
 * Copyright 2026 DigiCert, Inc. All Rights Reserved.
 *
 * DigiCert® TrustCore SDK and TrustEdge are licensed under a dual-license model:
 *
 * 1. **Open Source License**: GNU Affero General Public License v3.0 (AGPL v3).
 * See: https://github.com/digicert/trustcore/blob/main/LICENSE.md
 * 2. **Commercial License**: Available under DigiCert's Master Services Agreement.
 * See: https://www.digicert.com/master-services-agreement/
 *
 * *Use of TrustCore SDK or TrustEdge outside the scope of AGPL v3 requires a commercial license.*
 * *Contact DigiCert at sales@digicert.com for more details.*
 *
 */


/* Add to your makefile */
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"

#if ((defined(__ENABLE_DIGICERT_EAP_PEER__) || defined(__ENABLE_DIGICERT_EAP_AUTH__)) && (defined(__ENABLE_DIGICERT_SSL_ASYNC_SERVER_API__) || defined(__ENABLE_DIGICERT_SSL_ASYNC_CLIENT_API__)))

#if (defined(__ENABLE_DIGICERT_EAP_PEAP__))

#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../common/mstdlib.h"
#include "../common/mrtos.h"
#include "../common/vlong.h"
#include "../common/debug_console.h"
#include "../common/sizedbuffer.h"
#include "../crypto/ca_mgmt.h"
#include "../crypto/md5.h"
#include "../crypto/cert_store.h"
#include "../ssl/ssl.h"
#include "../common/redblack.h"
#include "../common/timer.h"
#include "../eap/eap.h"
#include "../eap/eap_proto.h"
#include "../eap/eap_auth.h"
#include "../eap/eap_tls.h"
#include "../eap/eap_md5.h"
#include "../eap/eap_mschapv2.h"
#include "../eap/eap_peap.h"
#include "../eap/eap_peap_pvt.h"
#include "../eap/eap_avp.h"
#include "../eap/eap_session.h"


/*------------------------------------------------------------------*/

/* prototypes */
static MSTATUS eap_PEAPsendPendingBytes(eapPEAPCB *tlscon, ubyte **eapRespData, ubyte4 *eapRespLen);

#define PEAP_KEYING_PHRASE_OLD            "client EAP encryption"
#define PEAP_KEYING_PHRASE_OLD_LEN        (21)
#define PEAP_KEYING_PHRASE_NEW            "client PEAP encryption"
#define PEAP_KEYING_PHRASE_NEW_LEN        (22)

/* SSL Record Header type */
#define SSL_CHANGE_CIPHER_SPEC              (20)
#define SSL_ALERT                           (21)
#define SSL_HANDSHAKE                       (22)
#define SSL_APPLICATION_DATA                (23)
/*------------------------------------------------------------------*/

/*! Process an encrypted PEAP payload.
This function processes an encrypted PEAP payload (in the form of
TLVs&mdash;type-length-values), performs any required fragmentation, and passes the
packet to the second phase of the PEAP stack.

\since 1.41
\version 1.41 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapPEAPCb    EAP-PEAP session handle returned from EAP_PEAPinitSession.
\param pkt          Pointer to encrypted PEAP packet.
\param pktLen       Number of bytes of encrypted PEAP data ($pkt$).

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPreceiveLLPacket(void * eapPEAPCb,ubyte *pkt,ubyte4 pktLen)
{
    eapPEAPCB* tlscon = (eapPEAPCB *)eapPEAPCb;
    MSTATUS    status = OK;
    ubyte*     eap_data = NULL;
    ubyte*     eapRespData;
    ubyte4     eapRespLen;
    ubyte*     eapClearRespData = NULL;
    ubyte4     eapClearRespLen =0;
    ubyte*     eapRemData = NULL;
    ubyte4     eapRemLen;
    /*intBoolean isTlsPkt = FALSE;*/
    ubyte      tlsType = 0;

    if (!tlscon)
    {
        status = ERR_EAP_TLS_SESSION_NOT_FOUND;
        goto exit;
    }
    /* We can recv 3 kinds of messages */
    /* Regular Message with L Flag */
    /* Frag Message with L & M Flag */
    /* Frag Message with  M Flag */
    /* Last Frag Message with  No Flag */
    /* Frag ACK Message Len ==1   */

    /*Initial Packet Generated by the PEAP App  */
    if (0 == pktLen)
        goto process;

    /*P: Verify Version before any other validation*/
    if (tlscon->eapPEAPparam.version != (*(pkt+1) & EAP_TLS_VERSION_MASK))
    {
        status = ERR_EAP_TLS_INVALID_VERSION;
        goto exit;
    }
    if (0 == tlscon->peap_frag_flag)
    {
        /* its an ACK or Other side has recd full pkt . */
        if (1 == pktLen || 2 == pktLen)
        {
            /* Here if we are Auth this must be the Cue for us to
               Start the 2nd Stage EAP BY initing the Stack and Send IdReq
            */

#if (defined(__ENABLE_DIGICERT_EAP_AUTH__))
            if (EAP_SESSION_TYPE_AUTHENTICATOR == tlscon->eapPEAPparam.sessionType)
                status = EAP_PEAPauthCreateSession(tlscon);
#endif

            goto exit;
        }

        if (!(*(pkt+1) & EAP_TLS_LENGTH_FLAG))
        {
            tlscon->peap_data_recv_total_len = pktLen - 2;
        }
        else
        {
            /* Copy The length Over */
            DIGI_MEMCPY((ubyte *) &tlscon->peap_data_recv_total_len, pkt+2, 4);
            tlscon->peap_data_recv_total_len = EAP_NTOHL(tlscon->peap_data_recv_total_len);
        }

        if ((*(pkt+1) & EAP_TLS_MORE_FLAG))
        {
           /* Move it to the buffer */
           tlscon->peap_data_recv = MALLOC(tlscon->peap_data_recv_total_len);

           if (NULL == tlscon->peap_data_recv)
           {
               status = ERR_MEM_ALLOC_FAIL;
               goto exit;
           }

           DIGI_MEMCPY(tlscon->peap_data_recv,pkt+6,pktLen-6);
           tlscon->peap_data_recv_len = pktLen - 6;
           tlscon->peap_frag_flag =  EAP_PEAP_FRAG_FLAG_RECV;
           /* Send ACK */
           /*Send ACK  1 Byte with Version*/
           eap_data = MALLOC(1);
           if (!eap_data)
           {
               status = ERR_MEM_ALLOC_FAIL;
               goto exit;
           }
           *eap_data = tlscon->eapPEAPparam.version;
           tlscon->eapPEAPparam.ulTransmit(tlscon->appSessionCB,eap_data,1,TRUE);
           goto exit;
        }
    }
    else
    {
        if (1 == pktLen || 2 == pktLen) /*its an ACK.. Send Pending Bytes */
        {
            if (EAP_PEAP_FRAG_FLAG_SEND == tlscon->peap_frag_flag)
            {
                status = eap_PEAPsendPendingBytes(tlscon,
                  &eapRespData, &eapRespLen);
                if (OK > status)
                    goto exit;
                tlscon->eapPEAPparam.ulTransmit(tlscon->appSessionCB,
                                                eapRespData,eapRespLen,TRUE);
                goto exit;
            }
            else
            {
                /* getting an ACK when we've already sent all the data.? */
                 status = ERR_EAP_TLS_NO_DATA_TO_SEND;
                 goto exit;
            }
        }
        else
        {
            if (EAP_PEAP_FRAG_FLAG_RECV == tlscon->peap_frag_flag)
            { /* coallese packets..  */
                if (pktLen + tlscon->peap_data_recv_len >= tlscon->peap_data_recv_total_len)
                {
                    /*Should be the last Fragment */
                    DIGI_MEMCPY(tlscon->peap_data_recv+tlscon->peap_data_recv_len,
                           pkt+1,pktLen-1);
                    tlscon->peap_data_recv_len += pktLen - 1;
                    tlscon->peap_frag_flag = 0;
                }
                else
                {
                    /* Should have the more flag set */
                    DIGI_MEMCPY(tlscon->peap_data_recv+tlscon->peap_data_recv_len,
                           pkt+2,pktLen-2);
                    tlscon->peap_data_recv_len += pktLen - 2;
                    /*Send ACK  1 Byte with Version*/
                    eap_data = MALLOC(1);
                    if (!eap_data)
                    {
                        status = ERR_MEM_ALLOC_FAIL;
                        goto exit;
                    }
                    *eap_data = tlscon->eapPEAPparam.version;
                    tlscon->eapPEAPparam.ulTransmit(tlscon->appSessionCB,eap_data,1,TRUE);
                    goto exit;
                }
            }
        }
    }

    if ((tlscon->peap_data_recv) && (tlscon->peap_data_recv_total_len))
    {
        /* Check to See whether a SSL APPLICATION or Handshake/Alert */
        tlsType = *tlscon->peap_data_recv;
        /*if (tlsType != SSL_APPLICATION_DATA)
            isTlsPkt = TRUE;*/
      /* First Decrypt the data packet */
        status = EAP_TLSRecvData((ubyte *)tlscon, tlscon->eapPEAPparam.tls_con,
                                 tlscon->peap_data_recv,
                                 tlscon->peap_data_recv_total_len,
                                 &eapClearRespData, &eapClearRespLen,
                                 &eapRemData, &eapRemLen);

        FREE(tlscon->peap_data_recv);
        tlscon->peap_data_recv = NULL;
        tlscon->peap_data_recv_total_len = 0;
        tlscon->peap_data_recv_len = 0;

        if (OK > status)
            goto exit;
    }
    else
    {
        if ((pkt) && (pktLen))
        {
            if (!(*(pkt+1) & EAP_TLS_LENGTH_FLAG))
            {
                tlsType = *(pkt+2);

                /*if (tlsType != SSL_APPLICATION_DATA)
                    isTlsPkt = TRUE;*/

                /* Data Starts an Offset 2 (PEAPByte,Flag Byte */
                status = EAP_TLSRecvData((ubyte *)tlscon,
                                     tlscon->eapPEAPparam.tls_con,
                                     pkt+2,pktLen-2,
                                     &eapClearRespData, &eapClearRespLen,
                                     &eapRemData, &eapRemLen);
            }
            else
            {
                /* Data Starts an Offset 6 (PEAPByte,Flag Byte,Length 4 Bytes */
                tlsType = *(pkt+6);

                /*if (tlsType != SSL_APPLICATION_DATA)
                    isTlsPkt = TRUE;*/

                status = EAP_TLSRecvData((ubyte *)tlscon,
                                     tlscon->eapPEAPparam.tls_con,
                                     pkt+6,pktLen -6,
                                     &eapClearRespData, &eapClearRespLen,
                                     &eapRemData, &eapRemLen);
            }
            if (OK > status)
                goto exit;

        }
    }

process:

    if (SSL_ALERT == tlsType)
    {
        sbyte4  alertClass;
        /*sbyte4  alertId;*/

        if (2 != eapClearRespLen)
        {
            status = ERR_SSL_PROTOCOL_BAD_LENGTH;
            goto exit;
        }

        if (NULL == eapClearRespData)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }

        alertClass = eapClearRespData[0];
        /*alertId    = eapClearRespData[1];*/

        if ( SSLALERTLEVEL_WARNING  == alertClass )
            status = ERR_SSL_WARNING_ALERT;
        else
            status = ERR_SSL_FATAL_ALERT;

        goto exit;

    }

    if (SSL_HANDSHAKE == tlsType)
    {
      /* Session Resumption */
      /* Inform the App about this  App to harvest data Out from the Send Buffer*/
        status = ERR_EAP_TLS_RECEIVED_HANDSHAKE;
        goto exit;

    }

#if (defined(__ENABLE_DIGICERT_EAP_PEER__))
    /* If Version 0 then directly we get a EAP Packet */
    if ((EAP_SESSION_TYPE_PEER == tlscon->eapPEAPparam.sessionType))
    {

        if (EAP_PEAP_EAP_INIT == tlscon->eapStatus)
        {
            /* Create 2nd Stage EAP Session and  just Send an Ack  */
            status = eap_PEAPPeerInit(eapPEAPCb);
            if (OK > status)
                goto exit;

            tlscon->eapStatus = EAP_PEAP_EAP_IDENTITY;
            eap_data = MALLOC(1);
            if (!eap_data)
            {
                status = ERR_MEM_ALLOC_FAIL;
                goto exit;
            }
            *eap_data = tlscon->eapPEAPparam.version;
            tlscon->eapPEAPparam.ulTransmit(tlscon->appSessionCB,eap_data,1,TRUE);
            goto exit;
        }

        /* Send the Packet Up */
        status = EAP_PEAPProcessEAPRequest(tlscon,eapClearRespData,
                                               eapClearRespLen);
        goto exit;
    }

#endif

#if (defined(__ENABLE_DIGICERT_EAP_AUTH__))
    if ((EAP_SESSION_TYPE_AUTHENTICATOR == tlscon->eapPEAPparam.sessionType))
    {
        if (NULL == tlscon->eapAuthSessionHdl)
        {
            status = EAP_PEAPauthCreateSession(tlscon);
            goto exit;
        }

        /* Send the Packet Up */
        status = EAP_PEAPProcessEAPRequest(tlscon,eapClearRespData,
                                               eapClearRespLen);
        goto exit;
    }
#endif

exit:
    return status;
}


/*------------------------------------------------------------------*/

static  MSTATUS
eap_PEAPsendPendingBytes(eapPEAPCB *tlscon,
                        ubyte **eapRespData, ubyte4 *eapRespLen)
{
    MSTATUS status = OK;
    ubyte *eapResponse = NULL;



    DEBUG_PRINTNL(DEBUG_EAP_MESSAGE, (sbyte *) "eap_PEAPsendPendingBytes: got here.");

    if (tlscon->eapMTU >= tlscon->peap_data_send_remaining)
    {
        *eapRespLen = tlscon->peap_data_send_remaining;
        eapResponse = (ubyte *) MALLOC(*eapRespLen);

        if (NULL == eapResponse)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }

        *eapResponse = tlscon->eapPEAPparam.version;
        tlscon->peap_data_send_remaining = 0;
        tlscon->peap_frag_flag = 0;
        FREE(tlscon->peap_data_send);
        tlscon->peap_data_send = NULL;
        tlscon->peap_data_send_cur = NULL;
    }
    else
    {
       /* Will need fragmentation */
        *eapRespLen = tlscon->eapMTU + 1;
        eapResponse = (ubyte *) MALLOC(*eapRespLen);
        if (NULL == eapResponse)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }
        *eapResponse = EAP_TLS_MORE_FLAG | (tlscon->eapPEAPparam.version & EAP_TLS_VERSION_MASK);
        tlscon->peap_data_send_remaining -= tlscon->eapMTU;
    }

    if (tlscon->peap_data_send_remaining)
    {
        status = DIGI_MEMCPY((eapResponse+1),tlscon->peap_data_send_cur,*eapRespLen-1);
        tlscon->peap_data_send_cur+=*eapRespLen - 1;
    }
    else /* Last Fragment */
        status = DIGI_MEMCPY(eapResponse,tlscon->peap_data_send_cur,*eapRespLen);

    *eapRespData = eapResponse;

exit:
    if (OK > status)
    {
        if (eapResponse)
            FREE(eapResponse);
    }

    return status;
}


/*------------------------------------------------------------------*/

/*! Build a PEAP packet.
This function builds a PEAP packet from the specified encrypted second stage
payload, prepending the header and performing any required fragmentation, and
returns the resultant packet through the $eapResponse$ parameter. Typically your
application passes the resulting packet to EAP for transmission from
authenticator to peer or from peer to authenticator.

\since 1.41
\version 1.41 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapPEAPCb    EAP-PEAP session handle returned from EAP_PEAPinitSession.
\param pkt          Pointer to payload to include in the PEAP packet.
\param pktLen       Number of bytes of payload data ($pkt$).
\param eapResponse  On return, pointer to resultant PEAP response packet.
\param eapRespLen   On return, number of bytes in EAP response payload ($eapResponse$).

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPFormSendPacket(void *eapPEAPCb,ubyte *pkt, ubyte4 pktLen,
                             ubyte **eapResponse, ubyte4 *eapRespLen)
{

    eapPEAPCB* tlscon = (eapPEAPCB *)eapPEAPCb;
    ubyte4     length;
    ubyte*     resp = NULL;
    MSTATUS    status = OK;

    if (!tlscon)
    {
        status = ERR_EAP_TLS_SESSION_NOT_FOUND;
        goto exit;
    }
    /*Create the PEAP Header with L or M bytes */

    *eapResponse = NULL;
    *eapRespLen =  0;

    /* No Need to send L Bit If the Second Stage payload does not need to
       to be fragmented . MS IAS does not like this */
    if (tlscon->eapMTU >= (pktLen + 1))
    {
        *eapRespLen = pktLen + 1;
        resp = MALLOC(*eapRespLen);

        if (NULL == resp)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }

        *resp = (tlscon->eapPEAPparam.version & EAP_TLS_VERSION_MASK);
        tlscon->peap_data_send_remaining = 0;
        DIGI_MEMCPY((ubyte *)(resp +1),(ubyte *)pkt,pktLen);
    }
    else
    {
       /* Will need fragmentation */
        *eapRespLen = tlscon->eapMTU + 5;
        resp = (ubyte *) MALLOC(*eapRespLen);
        if (NULL == resp)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }

        *resp = EAP_TLS_LENGTH_FLAG | EAP_TLS_MORE_FLAG | (tlscon->eapPEAPparam.version & EAP_TLS_VERSION_MASK);
        length = EAP_HTONL(pktLen);
        DIGI_MEMCPY(resp +1,(ubyte *)&length,4);
        tlscon->peap_data_send_remaining =pktLen - tlscon->eapMTU;
        tlscon->peap_frag_flag = EAP_PEAP_FRAG_FLAG_SEND;

        DIGI_MEMCPY(resp +5,(ubyte *)pkt+5,tlscon->eapMTU);
        /*Cache the packet for Future */
        tlscon->peap_data_send = pkt;
        tlscon->peap_data_send_cur = pkt+tlscon->eapMTU;
    }

    *eapResponse = resp;

exit:

    return status;

}


/*------------------------------------------------------------------*/

/*! Get a session's current status.
This function returns (through the $eapSessionStatus$ parameter) a session's
status.

\since 2.02
\version 2.02 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapPEAPCb        EAP-PEAP session handle returned from EAP_PEAPinitSession.
\param eapSessionStatus On return, pointer to session status structure.

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPgetSessionStatus(void * eapPEAPCb,ubyte  *eapSessionStatus)
{
    MSTATUS    status  = OK;
    eapPEAPCB* tlscon = (eapPEAPCB *)eapPEAPCb;

    if (!tlscon)
    {
        status = ERR_EAP_TLS_SESSION_NOT_FOUND;
        goto exit;
    }
    *eapSessionStatus = tlscon->sessionStatus;

exit:
    return status;

}


/*------------------------------------------------------------------*/

/*! Create and initialize an EAP-PEAP session.
This function creates and initializes an EAP-PEAP session based on the specified
parameters, returning the resultant session handle through the $eapPEAPSession$
parameter.

\since 1.41
\version 1.41 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param appSessionCB     Application session handle (cookie given by the application to identify the session).
\param eapPEAPSession   On return, pointer to EAP-PEAP session handle.
\param eapPEAPparams    Pointer to desired PEAP session parameters.


\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPinitSession(ubyte *appSessionCB,ubyte  **eapPEAPSession, EAP_PEAP_params *eapPEAPparams)
{

    eapPEAPCB* sessionCB = NULL;
    MSTATUS    status = OK;

    if ((NULL == eapPEAPparams) ||
        (NULL == eapPEAPparams->ulTransmit) ||
        (NULL == eapPEAPparams->tls_con) ||
        (NULL == eapPEAPparams->ul2ndStageReceive))
    {
        status = ERR_EAP_PEAP_MISSING_PARAMS;
        goto exit;
    }

    if ((EAP_SESSION_TYPE_PEER != eapPEAPparams->sessionType) &&
        (EAP_SESSION_TYPE_AUTHENTICATOR != eapPEAPparams->sessionType))
    {
        status = ERR_EAP_PEAP_MISSING_PARAMS;
        goto exit;
    }

    if (EAP_SESSION_TYPE_PEER == eapPEAPparams->sessionType)
    {
        if (0 == eapPEAPparams->UserNameLen)
        {
            status = ERR_EAP_PEAP_MISSING_PARAMS;
            goto exit;
        }
    }

    sessionCB = MALLOC(sizeof(eapPEAPCB));

    if (NULL == sessionCB)
    {
        status = ERR_MEM_ALLOC_FAIL;
        goto exit;
    }

    DIGI_MEMSET((ubyte *)sessionCB,0,sizeof(eapPEAPCB));

    DIGI_MEMCPY((ubyte *)&sessionCB->eapPEAPparam,(ubyte *)eapPEAPparams,
               sizeof(EAP_PEAP_params));

    status = EAP_TLSgetMTU(eapPEAPparams->tls_con, (ubyte *)&sessionCB->eapMTU);

    if(OK > status)
        goto exit;


    *eapPEAPSession = (void *)sessionCB;
    sessionCB->appSessionCB = appSessionCB;

exit:
    if (OK > status)
    {
        if (sessionCB)
        {
            FREE(sessionCB);
            sessionCB = NULL;
        }
    }

    return status;
}


/*------------------------------------------------------------------*/

/*! Delete an EAP-PEAP session.
This function deletes an EAP-PEAP session.

\since 1.41
\version 1.41 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapPEAPSession   EAP-PEAP session handle returned from EAP_PEAPinitSession.

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPdeleteSession(void *eapPEAPSession)
{
    /* Free any Pending Fragment Buffers */
    eapPEAPCB*  tlscon = (eapPEAPCB*) eapPEAPSession;
    MSTATUS status = OK;

    if (!tlscon)
    {
        status = ERR_EAP_TLS_SESSION_NOT_FOUND;
        goto exit;
    }

    if (tlscon->peap_data_send)
        FREE(tlscon->peap_data_send);

    if (tlscon->peap_data_recv)
        FREE(tlscon->peap_data_recv);

    if ((EAP_SESSION_TYPE_PEER == tlscon->eapPEAPparam.sessionType) &&
        (tlscon->eapSessionHdl))
        EAP_sessionDelete(tlscon->eapSessionHdl,tlscon->eapPEAPparam.instanceId);
    if ((EAP_SESSION_TYPE_AUTHENTICATOR == tlscon->eapPEAPparam.sessionType) &&
        (tlscon->eapAuthSessionHdl))
        EAP_sessionDelete(tlscon->eapAuthSessionHdl,tlscon->eapPEAPparam.instanceId);

    FREE(eapPEAPSession);
exit:
    return status;
}

/*------------------------------------------------------------------*/

/* Doc Note: This function is for Mocana internal code use only, and should not
be included in the API documentation.
*/
extern MSTATUS
EAP_PEAPProcessEAPRequest(eapPEAPCB *eapCb, ubyte *pkt, ubyte4 pktLen)
{
   /* Pass the packet up  to the Peer  Second Stage*/
    MSTATUS    status = OK;
    eapHdr_t*  eapHdr;
    ubyte*     newPkt = pkt;

    if ((0 == eapCb->eapPEAPparam.version) ||
        (1 == pktLen) )
    {
        if (NULL == pkt)
        {
            status = ERR_NULL_POINTER;
            goto exit;
        }

        /* If the Type is TLV then the Other Side sends a Full EAP Header */

        if ((EAP_CODE_REQUEST == *pkt)  ||
            (EAP_CODE_RESPONSE == *pkt))
        {
            if (4 < pktLen)
            {
                if (EAP_TYPE_TLV == *(pkt+4))
                    goto process;

            }
        }

    /* Add the EAP Hdr for Peap Version 0 */
        newPkt    = MALLOC(sizeof(eapHdr)+pktLen);
        if (NULL == newPkt)
        {
            status = ERR_MEM_ALLOC_FAIL;
            goto exit;
        }

        eapHdr = (eapHdr_t *)newPkt;

        eapHdr->code = eapCb->recvCode;
        eapHdr->id   = eapCb->recvId;
        /* Set the Length */
        DIGI_HTONS(newPkt + 2,sizeof(eapHdr_t) + pktLen);

        DIGI_MEMCPY(newPkt + sizeof(eapHdr_t),pkt,pktLen);
        pktLen += sizeof(eapHdr_t);
    }

process:


    if ((EAP_SESSION_TYPE_PEER == eapCb->eapPEAPparam.sessionType))
    {
        status = EAP_llReceivePacket(eapCb->eapSessionHdl,
                                     eapCb->eapPEAPparam.instanceId,
                                     newPkt,pktLen,NULL);
    }
    else
    {
        status = EAP_llReceivePacket(eapCb->eapAuthSessionHdl,
                                     eapCb->eapPEAPparam.instanceId,
                                     newPkt,pktLen,NULL);
    }


exit:
    if ((newPkt)  && (newPkt !=pkt))
        FREE(newPkt);

    return status;

}


/*------------------------------------------------------------------*/

/* Doc Note: This function is for Mocana internal code use only, and should not
be included in the API documentation.
*/
extern MSTATUS
EAP_PEAPBuildResultTlv(ubyte2 intResult, ubyte *buf, ubyte4 *length)
{
    ubyte* ptr = buf;

    *ptr++ = 0x80;
    *ptr++ = EAP_PEAP_RESULT_TLV; /* 3*/
    *ptr++ = 0;
    *ptr++ = 2;
    *ptr++ = intResult >> 8;
    *ptr++ = intResult;
    *length = 6;
    return OK;
}


/*------------------------------------------------------------------*/

/* Doc Note: This function is for Mocana internal code use only, and should not
be included in the API documentation.
*/
extern MSTATUS
EAP_PEAPgetTLVbyType(eapPEAPCB *eapCb, ubyte *pPkt, ubyte4 pktLen, ubyte2 type,
                     ubyte2 *pTlvLen, ubyte **pData, ubyte *isMandatory)
{
    ubyte2 tlvType;
    ubyte* ptr = pPkt;
    ubyte2 tlv_len = 0;
    ubyte2 len;
    MSTATUS status = ERR_EAP_TLV_NOT_FOUND;

    *isMandatory = FALSE;
    *pData = NULL;

    while (ptr)
    {
        tlvType = DIGI_NTOHS(ptr) & 0x3fff;
        DIGI_MEMCPY((ubyte *)&len, (ptr + 2), 2);
        len = EAP_NTOHS(len);
        if (tlvType == type)
        {
            if (*ptr & 0x80)
                *isMandatory = TRUE;
            *pTlvLen = len;
            *pData = ptr + 4;
            status = OK;
            break;
        }
        tlv_len += len + 4;
        if (tlv_len < pktLen)
            ptr += tlv_len;
        else
            break;
    }
    return status;
}


/*------------------------------------------------------------------*/

/* Doc Note: This function is for Mocana internal code use only, and should not
be included in the API documentation.
*/
extern  MSTATUS
EAP_PEAP_llTransmitPktCallback(ubyte *appSessionHdl,
                          eapHdr_t *eap_hdr,
                          ubyte *eap_data,
                          ubyte4 eap_data_len)
{
    eapPEAPCB*  eapCb = (eapPEAPCB *) appSessionHdl;
    ubyte*      response = NULL;
    ubyte4      responseLen;
    MSTATUS     status = OK;

    if (NULL == eapCb)
    {
        status = ERR_EAP_INVALID_SESSION;
        goto exit;
    }

    response = MALLOC(eap_data_len);

    if (NULL == response)
    {
        status = ERR_MEM_ALLOC_FAIL;
        goto exit;
    }

    DIGI_MEMCPY(response,eap_data,eap_data_len);
    /* PEAP Version 0 , No Header Sent except for Type TLV */

    if (0 == eapCb->eapPEAPparam.version)
    {
        if ((EAP_CODE_REQUEST == eap_hdr->code) ||
            (EAP_CODE_RESPONSE == eap_hdr->code))
        {
            if (4 < eap_data_len)
            {
               if(EAP_TYPE_TLV == *(eap_data))
               {
                   FREE(response);
                   response = NULL;
                   goto process;
               }

            }
        }
        eapCb->eapPEAPparam.ulTransmit(eapCb->appSessionCB,
                                       response,eap_data_len,FALSE);
        goto exit;

    }

process:
    FREE(response);
    response = NULL;

    response = MALLOC(sizeof(eapHdr_t)+eap_data_len);

    responseLen =  (sizeof(eapHdr_t)+eap_data_len);

    if (NULL == response)
    {
        status = ERR_MEM_ALLOC_FAIL;
        goto exit;
    }

    DIGI_MEMCPY(response,(ubyte *)eap_hdr,sizeof(eapHdr_t));
    DIGI_MEMCPY(response+sizeof(eapHdr_t),eap_data,eap_data_len);

    /*Call First Stage*/
    eapCb->eapPEAPparam.ulTransmit(eapCb->appSessionCB,
                                   response, responseLen, FALSE);

exit:
    return status;
}

/*------------------------------------------------------------------*/

/*! Assign the code and ID values to an inner EAP header.
This function assigns the specified code and ID values to an inner EAP header.
Typically this is used in PEAP v0 when the authenticator or peer has not sent
the inner header information, which is required by the inner (second stage) EAP
state machine for packet processing.

\since 2.02
\version 2.02 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapCB    EAP-PEAP session handle returned from EAP_PEAPinitSession.
\param code     Any of the $eapCode$ enumerated values (defined in eap_proto.h).
\param id       EAP request header ID (unique to this session).

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPSetEapHdr(void  *eapCB, eapCode code, ubyte id)
{
    eapPEAPCB*  eapCb = (eapPEAPCB *) eapCB;
    MSTATUS status = OK;

    if (NULL == eapCb)
    {
        status = ERR_EAP_INVALID_SESSION;
        goto exit;
    }
    eapCb->recvCode = code;
    eapCb->recvId   = id;

exit:
    return status ;
}

/*------------------------------------------------------------------*/

/*! Generate and return a session's authentication keys.
This function generates and returns a session's authentication keys.

\since 2.02
\version 2.02 and later

! Flags
To enable this function, the following flag must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEAP__$

Additionally, at least one of the following flags must be defined in moptions.h:
- $__ENABLE_DIGICERT_EAP_PEER__$
- $__ENABLE_DIGICERT_EAP_AUTH__$

#Include %file:#&nbsp;&nbsp;eap_peap.h

\param eapCb        EAP-PEAP session handle returned from EAP_PEAPinitSession.
\param key          On return, pointer to authentication keys.
\param keyLen       Number of bytes desired in the authentication key.

\return $OK$ (0) if successful; otherwise a negative number error code
definition from merrors.h. To retrieve a string containing an English text
error identifier corresponding to the function's returned error status, use the
$DISPLAY_ERROR$ macro.

*/
extern MSTATUS
EAP_PEAPgetKey(void *eapCb,ubyte *key,ubyte2 keyLen/* 128 or 192 Bytes */)
{
   /* Generate key based upon the TLS Expansion Key Algo */
    eapPEAPCB * eapPEAPCb = (eapPEAPCB *) eapCb;
    MSTATUS status;

    if (NULL == eapPEAPCb)
    {
        status = ERR_EAP_INVALID_SESSION;
        goto exit;
    }

    if (eapPEAPCb->eapPEAPparam.version < 1)
        status = SSL_generateTLSExpansionKey(
                                    eapPEAPCb->eapPEAPparam.connectionInstance,
                                    key,keyLen,(ubyte *) PEAP_KEYING_PHRASE_OLD,
                                    PEAP_KEYING_PHRASE_OLD_LEN);
    else
        status = SSL_generateTLSExpansionKey(
                                    eapPEAPCb->eapPEAPparam.connectionInstance,
                                    key,keyLen,(ubyte *) PEAP_KEYING_PHRASE_NEW,
                                    PEAP_KEYING_PHRASE_NEW_LEN);

exit:
    return status;
}

/*------------------------------------------------------------------*/

#endif /*(defined(__ENABLE_DIGICERT_EAP_PEAP__)) */
#endif /* ((defined(__ENABLE_DIGICERT_EAP_PEER__) || defined(__ENABLE_DIGICERT_EAP_AUTH__)) */
