/*
 * e_moc_evp_err.c
 *
 * Copyright 2026 DigiCert Project Authors. All Rights Reserved.
 *
 * DigiCert® TrustCore and TrustEdge are licensed under a dual-license model:
 * - **Open Source License**: GNU AGPL v3. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE
 * - **Commercial License**: Available under DigiCert’s Master Services Agreement. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE_COMMERCIAL.txt
 *   or https://www.digicert.com/master-services-agreement/
 *
 * For commercial licensing, contact DigiCert at sales@digicert.com.*
 *
 */

/*
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "e_moc_evp_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA MOC_EVP_str_functs[] = {
    {ERR_FUNC(MOC_EVP_F_BIND), "bind_moc_evp"},
    {0, NULL}
};

static ERR_STRING_DATA MOC_EVP_str_reasons[] = {
    {ERR_REASON(MOC_EVP_R_INIT_FAILED), "init failed"},
    {ERR_REASON(MOC_EVP_R_MEM_ALLOC_FAILED), "mem alloc failed"},
    {0, NULL}
};

#endif

#ifdef MOC_EVP_LIB_NAME
static ERR_STRING_DATA MOC_EVP_lib_name[] = {
    {0, MOC_EVP_LIB_NAME},
    {0, NULL}
};
#endif

static int MOC_EVP_lib_error_code = 0;
static int MOC_EVP_error_init = 1;

void ERR_load_DIGI_EVP_strings(void)
{
    if (MOC_EVP_lib_error_code == 0)
        MOC_EVP_lib_error_code = ERR_get_next_error_library();

    if (MOC_EVP_error_init) {
        MOC_EVP_error_init = 0;
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(MOC_EVP_lib_error_code, MOC_EVP_str_functs);
        ERR_load_strings(MOC_EVP_lib_error_code, MOC_EVP_str_reasons);
#endif

#ifdef MOC_EVP_LIB_NAME
        MOC_EVP_lib_name->error = ERR_PACK(MOC_EVP_lib_error_code, 0, 0);
        ERR_load_strings(0, MOC_EVP_lib_name);
#endif
    }
}

void ERR_unload_DIGI_EVP_strings(void)
{
    if (MOC_EVP_error_init == 0) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(MOC_EVP_lib_error_code, MOC_EVP_str_functs);
        ERR_unload_strings(MOC_EVP_lib_error_code, MOC_EVP_str_reasons);
#endif

#ifdef MOC_EVP_LIB_NAME
        ERR_unload_strings(0, MOC_EVP_lib_name);
#endif
        MOC_EVP_error_init = 1;
    }
}

void ERR_DIGI_EVP_error(int function, int reason, char *file, int line)
{
    if (MOC_EVP_lib_error_code == 0)
        MOC_EVP_lib_error_code = ERR_get_next_error_library();
    ERR_PUT_error(MOC_EVP_lib_error_code, function, reason, file, line);
}
