/**
 * @file sapi2_serialize.c
 * @brief This file contains SAPI2 Serialization related functions for TPM2.
 *
 * @flags
 *  To enable this file's functions, the following flags must be defined in
 * moptions.h:
 *
 *  + \c \__ENABLE_DIGICERT_TPM2__
 *
 * Copyright 2025 DigiCert Project Authors. All Rights Reserved.
 * 
 * DigiCert® TrustCore and TrustEdge are licensed under a dual-license model:
 * - **Open Source License**: GNU AGPL v3. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE
 * - **Commercial License**: Available under DigiCert’s Master Services Agreement. See: https://github.com/digicert/trustcore-test/blob/main/LICENSE_COMMERCIAL.txt  
 *   or https://www.digicert.com/master-services-agreement/
 * 
 * *For commercial licensing, contact DigiCert at sales@digicert.com.*
 *
 */

#include "../../../../common/moptions.h"

#if (defined(__ENABLE_DIGICERT_TPM2__) || defined(__ENABLE_DIGICERT_SMP_PKCS11__))

#ifdef __ENABLE_DIGICERT_SMP_PKCS11__
#define __ENABLE_DIGICERT_TPM2__
#endif

#include "../../../../common/mtypes.h"
#include "../../../../common/merrors.h"
#include "../../../../common/mocana.h"
#include "../../../../common/mdefs.h"
#include "../../../../common/mstdlib.h"
#include "../../../../common/debug_console.h"
#include "../tpm2_types.h"
#include "sapi2_serialize.h"
#include "../tap_serialize_tpm2.h"

typedef struct sapi2_type_map {
    SAPI2_SERIALIZE_TYPE type;
    const tpm2_shadow_struct *root;
} sapi2_type_map;

static const sapi2_type_map type_map[] = {
    {SAPI2_ST_UBYTE2, &TAP_SHADOW_ubyte2},
    {SAPI2_ST_UBYTE8, &TAP_SHADOW_ubyte8},
    {SAPI2_ST_TPM2_HANDLE, &TPM2_SHADOW_TPM2_HANDLE},
    {SAPI2_ST_TPMA_NV, &TPM2_SHADOW_TPMA_NV},
    {SAPI2_ST_TPM2_ALG_ID, &TPM2_SHADOW_TPM2_ALG_ID},
    {SAPI2_ST_TPMI_RH_NV_INDEX, &TPM2_SHADOW_TPMI_RH_NV_INDEX},
    {SAPI2_ST_TPMI_ALG_HASH, &TPM2_SHADOW_TPMI_ALG_HASH},
    {SAPI2_ST_TPM2B_DIGEST, &TPM2_SHADOW_TPM2B_DIGEST},
    {SAPI2_ST_TPMS_NV_PUBLIC, &TPM2_SHADOW_TPMS_NV_PUBLIC},
    {SAPI2_ST_TPMT_PUBLIC, &TPM2_SHADOW_TPMT_PUBLIC},
    {SAPI2_ST_TPM2_START_AUTH_SESSION_CMD_HANDLES, &TPM2_SHADOW_TPM2_START_AUTH_SESSION_CMD_HANDLES},
    {SAPI2_ST_TPM2_START_AUTH_SESSION_CMD_PARAMS, &TPM2_SHADOW_TPM2_START_AUTH_SESSION_CMD_PARAMS},
    {SAPI2_ST_TPM2_START_AUTH_SESSION_RSP_HANDLES, &TPM2_SHADOW_TPM2_START_AUTH_SESSION_RSP_HANDLES},
    {SAPI2_ST_TPM2_START_AUTH_SESSION_RSP_PARAMS, &TPM2_SHADOW_TPM2_START_AUTH_SESSION_RSP_PARAMS},
    {SAPI2_ST_TPM2_COMMAND_HEADER, &TPM2_SHADOW_TPM2_COMMAND_HEADER},
    {SAPI2_ST_TPM2_RESPONSE_HEADER, &TPM2_SHADOW_TPM2_RESPONSE_HEADER},
    {SAPI2_ST_TPMS_AUTH_COMMAND, &TPM2_SHADOW_TPMS_AUTH_COMMAND},
    {SAPI2_ST_TPMS_AUTH_RESPONSE, &TPM2_SHADOW_TPMS_AUTH_RESPONSE},
    {SAPI2_ST_TPM2B_AUTH, &TPM2_SHADOW_TPM2B_AUTH},
    {SAPI2_ST_TPMI_RH_HIERARCHY_AUTH, &TPM2_SHADOW_TPMI_RH_HIERARCHY_AUTH},
    {SAPI2_ST_TPM2_GET_CAPABILITY_CMD_PARAMS, &TPM2_SHADOW_TPM2_GET_CAPABILITY_CMD_PARAMS},
    {SAPI2_ST_TPM2_GET_CAPABILITY_RSP_PARAMS, &TPM2_SHADOW_TPM2_GET_CAPABILITY_RSP_PARAMS},
    {SAPI2_ST_TPMS_CAPABILITY_DATA, &TPM2_SHADOW_TPMS_CAPABILITY_DATA},
    {SAPI2_ST_TPMI_YES_NO, &TPM2_SHADOW_TPMI_YES_NO},
    {SAPI2_ST_TPML_ALG_PROPERTY, &TPM2_SHADOW_TPML_ALG_PROPERTY},
    {SAPI2_ST_TPML_HANDLE, &TPM2_SHADOW_TPML_HANDLE},
    {SAPI2_ST_TPML_CCA, &TPM2_SHADOW_TPML_CCA},
    {SAPI2_ST_TPML_CC, &TPM2_SHADOW_TPML_CC},
    {SAPI2_ST_TPML_PCR_SELECTION, &TPM2_SHADOW_TPML_PCR_SELECTION},
    {SAPI2_ST_TPMS_PCR_SELECTION, &TPM2_SHADOW_TPMS_PCR_SELECTION},
    {SAPI2_ST_TPML_TAGGED_TPM_PROPERTY, &TPM2_SHADOW_TPML_TAGGED_TPM_PROPERTY},
    {SAPI2_ST_TPML_TAGGED_PCR_PROPERTY, &TPM2_SHADOW_TPML_TAGGED_PCR_PROPERTY},
    {SAPI2_ST_TPML_ECC_CURVE, &TPM2_SHADOW_TPML_ECC_CURVE},
    {SAPI2_ST_TPMS_TAGGED_PROPERTY, &TPM2_SHADOW_TPMS_TAGGED_PROPERTY},
    {SAPI2_ST_TPM2_PT, &TPM2_SHADOW_TPM2_PT},
    {SAPI2_ST_TPML_PCR_SELECT, &TPM2_SHADOW_TPML_PCR_SELECT},
    {SAPI2_ST_TPMA_CC, &TPM2_SHADOW_TPMA_CC},
    {SAPI2_ST_TPMS_ALG_PROPERTY, &TPM2_SHADOW_TPMS_ALG_PROPERTY},
    {SAPI2_ST_TPMA_ALGORITHM, &TPM2_SHADOW_TPMA_ALGORITHM},
    {SAPI2_ST_TPM2_CAP, &TPM2_SHADOW_TPM2_CAP},
    {SAPI2_ST_TPMI_RH_HIERARCHY, &TPM2_SHADOW_TPMI_RH_HIERARCHY},
    {SAPI2_ST_TPM2_CREATE_PRIMARY_CMD_PARAMS, &TPM2_SHADOW_TPM2_CREATE_PRIMARY_CMD_PARAMS},
    {SAPI2_ST_TPM2_CREATE_PRIMARY_RSP_PARAMS, &TPM2_SHADOW_TPM2_CREATE_PRIMARY_RSP_PARAMS},
    {SAPI2_ST_TPMI_DH_OBJECT, &TPM2_SHADOW_TPMI_DH_OBJECT},
    {SAPI2_ST_TPM2_CREATE_CMD_PARAMS, &TPM2_SHADOW_TPM2_CREATE_CMD_PARAMS},
    {SAPI2_ST_TPM2_CREATE_RSP_PARAMS, &TPM2_SHADOW_TPM2_CREATE_RSP_PARAMS},
    {SAPI2_ST_TPM2_DUPLICATE_CMD_PARAMS, &TPM2_SHADOW_TPM2_DUPLICATE_CMD_PARAMS},
    {SAPI2_ST_TPM2_DUPLICATE_RSP_PARAMS, &TPM2_SHADOW_TPM2_DUPLICATE_RSP_PARAMS},
    {SAPI2_ST_TPM2_DUPLICATE_CMD_HANDLES, &TPM2_SHADOW_TPM2_DUPLICATE_CMD_HANDLES},
    {SAPI2_ST_TPM2_FAPI2_DUPLICATEOUT, &TPM2_SHADOW_FAPI2_DuplicateOut},
    {SAPI2_ST_TPM2_IMPORT_CMD_PARAMS, &TPM2_SHADOW_TPM2_IMPORT_CMD_PARAMS},
    {SAPI2_ST_TPM2_IMPORT_RSP_PARAMS, &TPM2_SHADOW_TPM2_IMPORT_RSP_PARAMS},
    {SAPI2_ST_TPM2_LOAD_CMD_PARAMS, &TPM2_SHADOW_TPM2_LOAD_CMD_PARAMS},
    {SAPI2_ST_TPM2_LOAD_RSP_PARAMS, &TPM2_SHADOW_TPM2_LOAD_RSP_PARAMS},
    {SAPI2_ST_TPM2_FLUSH_CONTEXT_CMD_PARAMS, &TPM2_SHADOW_TPM2_FLUSH_CONTEXT_CMD_PARAMS},
    {SAPI2_ST_TPM2_NV_DEFINE_SPACE_CMD_PARAMS, &TPM2_SHADOW_TPM2_NV_DEFINE_SPACE_CMD_PARAMS},
    {SAPI2_ST_TPMI_RH_PROVISION, &TPM2_SHADOW_TPMI_RH_PROVISION},
    {SAPI2_ST_TPM2_NV_UNDEFINE_SPACE_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_UNDEFINE_SPACE_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_WRITE_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_WRITE_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_WRITE_CMD_PARAMS, &TPM2_SHADOW_TPM2_NV_WRITE_CMD_PARAMS},
    {SAPI2_ST_TPM2_NV_READ_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_READ_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_READ_CMD_PARAMS, &TPM2_SHADOW_TPM2_NV_READ_CMD_PARAMS},
    {SAPI2_ST_TPM2_NV_READ_RSP_PARAMS, &TPM2_SHADOW_TPM2_NV_READ_RSP_PARAMS},
    {SAPI2_ST_TPM2_NV_READ_PUBLIC_RSP_PARAMS, &TPM2_SHADOW_TPM2_NV_READ_PUBLIC_RSP_PARAMS},
    {SAPI2_ST_TPM2B_SENSITIVE_DATA, &TPM2_SHADOW_TPM2B_SENSITIVE_DATA},
    {SAPI2_ST_TPMI_DH_PCR, &TPM2_SHADOW_TPMI_DH_PCR},
    {SAPI2_ST_TPML_DIGEST_VALUES, &TPM2_SHADOW_TPML_DIGEST_VALUES},
    {SAPI2_ST_TPML_DIGEST, &TPM2_SHADOW_TPML_DIGEST},
    {SAPI2_ST_TPM2_PCR_READ_RSP_PARAMS, &TPM2_SHADOW_TPM2_PCR_READ_RSP_PARAMS},
    {SAPI2_ST_TPM2B_EVENT, &TPM2_SHADOW_TPM2B_EVENT},
    {SAPI2_ST_TPM2_GET_TEST_RESULT_RSP_PARAMS, &TPM2_SHADOW_TPM2_GET_TEST_RESULT_RSP_PARAMS},
    {SAPI2_ST_TPM2_READ_PUBLIC_RSP_PARAMS, &TPM2_SHADOW_TPM2_READ_PUBLIC_RSP_PARAMS},
    {SAPI2_ST_TPMI_ECC_CURVE, &TPM2_SHADOW_TPMI_ECC_CURVE},
    {SAPI2_ST_TPMS_ALGORITHM_DETAIL_ECC, &TPM2_SHADOW_TPMS_ALGORITHM_DETAIL_ECC},
    {SAPI2_ST_TPM2_RSA_ENCRYPT_CMD_PARAMS, &TPM2_SHADOW_TPM2_RSA_ENCRYPT_CMD_PARAMS},
    {SAPI2_ST_TPM2B_DATA, &TPM2_SHADOW_TPM2B_DATA},
    {SAPI2_ST_TPM2B_PUBLIC_KEY_RSA, &TPM2_SHADOW_TPM2B_PUBLIC_KEY_RSA},
    {SAPI2_ST_TPM2_RSA_DECRYPT_CMD_PARAMS, &TPM2_SHADOW_TPM2_RSA_DECRYPT_CMD_PARAMS},
    {SAPI2_ST_TPM2_SIGN_CMD_PARAMS, &TPM2_SHADOW_TPM2_SIGN_CMD_PARAMS},
    {SAPI2_ST_TPMT_SIGNATURE, &TPM2_SHADOW_TPMT_SIGNATURE},
    {SAPI2_ST_TPM2_VERIFY_SIGNATURE_CMD_PARAMS, &TPM2_SHADOW_TPM2_VERIFY_SIGNATURE_CMD_PARAMS},
    {SAPI2_ST_TPMT_TK_VERIFIED, &TPM2_SHADOW_TPMT_TK_VERIFIED},
    {SAPI2_ST_TPM2_ENCRYPT_DECRYPT_CMD_PARAMS, &TPM2_SHADOW_TPM2_ENCRYPT_DECRYPT_CMD_PARAMS},
    {SAPI2_ST_TPM2_ENCRYPT_DECRYPT2_CMD_PARAMS, &TPM2_SHADOW_TPM2_ENCRYPT_DECRYPT2_CMD_PARAMS},
    {SAPI2_ST_TPM2_ENCRYPT_DECRYPT_RSP_PARAMS, &TPM2_SHADOW_TPM2_ENCRYPT_DECRYPT_RSP_PARAMS},
    {SAPI2_ST_TPM2_HIERARCHY_CONTROL_CMD_PARAMS, &TPM2_SHADOW_TPM2_HIERARCHY_CONTROL_CMD_PARAMS},
    {SAPI2_ST_TPM2_EVICT_CONTROL_CMD_HANDLES, &TPM2_SHADOW_TPM2_EVICT_CONTROL_CMD_HANDLES},
    {SAPI2_ST_TPMI_DH_PERSISTENT, &TPM2_SHADOW_TPMI_DH_PERSISTENT},
    {SAPI2_ST_TPMI_RH_CLEAR, &TPM2_SHADOW_TPMI_RH_CLEAR},
    {SAPI2_ST_TPM2_NV_INCREMENT_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_INCREMENT_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_EXTEND_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_EXTEND_CMD_HANDLES},
    {SAPI2_ST_TPM2B_MAX_NV_BUFFER, &TPM2_SHADOW_TPM2B_MAX_NV_BUFFER},
    {SAPI2_ST_TPM2_NV_SET_BITS_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_SET_BITS_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_WRITE_LOCK_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_WRITE_LOCK_CMD_HANDLES},
    {SAPI2_ST_TPM2_NV_READ_LOCK_CMD_HANDLES, &TPM2_SHADOW_TPM2_NV_READ_LOCK_CMD_HANDLES},
    {SAPI2_ST_TPM2B_PRIVATE, &TPM2_SHADOW_TPM2B_PRIVATE},
    {SAPI2_ST_TPM2B_PUBLIC, &TPM2_SHADOW_TPM2B_PUBLIC},
    {SAPI2_ST_TPM2B_NV_PUBLIC, &TPM2_SHADOW_TPM2B_NV_PUBLIC},
    {SAPI2_ST_TPM2B_CREATION_DATA, &TPM2_SHADOW_TPM2B_CREATION_DATA},
    {SAPI2_ST_TPMT_TK_CREATION, &TPM2_SHADOW_TPMT_TK_CREATION},
    {SAPI2_ST_TPM2B_SENSITIVE, &TPM2_SHADOW_TPM2B_SENSITIVE},
    {SAPI2_ST_TPM2_LOAD_EXTERNAL_CMD_PARAMS, &TPM2_SHADOW_TPM2_LOAD_EXTERNAL_CMD_PARAMS},
    {SAPI2_ST_TPM2_LOAD_EXTERNAL_CMD_PARAMS2, &TPM2_SHADOW_TPM2_LOAD_EXTERNAL_CMD_PARAMS2},
    {SAPI2_ST_TPM2B_NAME, &TPM2_SHADOW_TPM2B_NAME},
    {SAPI2_ST_TPM2_OBJECT_CHANGE_AUTH_CMD_HANDLES, &TPM2_SHADOW_TPM2_OBJECT_CHANGE_AUTH_CMD_HANDLES},
    {SAPI2_ST_TPM2_SHADOW_TPM2_HASH_SEQUENCE_START_CMD_PARAMS, &TPM2_SHADOW_TPM2_HASH_SEQUENCE_START_CMD_PARAMS},
    {SAPI2_ST_TPM2B_MAX_BUFFER, &TPM2_SHADOW_TPM2B_MAX_BUFFER},
    {SAPI2_ST_TPM2_SHADOW_TPM2_SEQUENCE_COMPLETE_CMD_PARAMS, &TPM2_SHADOW_TPM2_SEQUENCE_COMPLETE_CMD_PARAMS},
    {SAPI2_ST_TPM2_SHADOW_TPM2_SEQUENCE_COMPLETE_RSP_PARAMS, &TPM2_SHADOW_TPM2_SEQUENCE_COMPLETE_RSP_PARAMS},
    {SAPI2_ST_TPM2_SHADOW_TPM2_MAKE_CREDENTIAL_CMD_PARAMS,&TPM2_SHADOW_TPM2_MAKE_CREDENTIAL_CMD_PARAMS},
    {SAPI2_ST_TPM2_SHADOW_TPM2_MAKE_CREDENTIAL_RSP_PARAMS,&TPM2_SHADOW_TPM2_MAKE_CREDENTIAL_RSP_PARAMS},
    {SAPI2_ST_TPM2_ACTIVATE_CREDENTIAL_CMD_HANDLES, &TPM2_SHADOW_TPM2_ACTIVATE_CREDENTIAL_CMD_HANDLES},
    {SAPI2_ST_TPM2_QUOTE_CMD_PARAMS, &TPM2_SHADOW_TPM2_QUOTE_CMD_PARAMS},
    {SAPI2_ST_TPM2_QUOTE_RSP_PARAMS, &TPM2_SHADOW_TPM2_QUOTE_RSP_PARAMS},
    {SAPI2_ST_TPM2_TPMS_ATTEST, &TPM2_SHADOW_TPMS_ATTEST},
    {SAPI2_ST_TPM2_AK_CSR_INFO, &TPM2_SHADOW_TPM2_AK_CSR_INFO},
    {SAPI2_ST_TPM2_POLICY_AUTHORIZE_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_AUTHORIZE_CMD_PARAMS},
    {SAPI2_ST_TPM2_POLICY_PCR_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_PCR_CMD_PARAMS},
    {SAPI2_ST_TPM2_POLICY_AUTHORIZE_NV_CMD_HANDLES, &TPM2_SHADOW_TPM2_POLICY_AUTHORIZE_NV_CMD_HANDLES},
    {SAPI2_ST_TPM2_POLICY_SECRET_CMD_HANDLES, &TPM2_SHADOW_TPM2_POLICY_SECRET_CMD_HANDLES},
    {SAPI2_ST_TPM2_POLICY_SECRET_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_SECRET_CMD_PARAMS},
    {SAPI2_ST_TPM2_POLICY_SECRET_RSP_PARAMS, &TPM2_SHADOW_TPM2_POLICY_SECRET_RSP_PARAMS},
    {SAPI2_ST_TPM2_POLICY_SIGNED_CMD_HANDLES, &TPM2_SHADOW_TPM2_POLICY_SIGNED_CMD_HANDLES},
    {SAPI2_ST_TPM2_POLICY_SIGNED_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_SIGNED_CMD_PARAMS},
    {SAPI2_ST_TPM2_POLICY_SIGNED_RSP_PARAMS, &TPM2_SHADOW_TPM2_POLICY_SIGNED_RSP_PARAMS},
    {SAPI2_ST_TPMI_RH_DA_LOCK_RESET, &TPM2_SHADOW_TPMI_RH_DA_LOCK_RESET},
    {SAPI2_ST_TPM2_POLICY_DUPLICATIONSELECT_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_DUPLICATIONSELECT_CMD_PARAMS},
    {SAPI2_ST_TPM2_POLICY_COMMANDCODE_CMD_PARAMS, &TPM2_SHADOW_TPM2_POLICY_COMMANDCODE_CMD_PARAMS},
    {SAPI2_ST_TPMI_RH_DA_LOCK_PARAMETERS, &TPM2_SHADOW_TPMI_RH_DA_LOCK_PARAMETERS},
    {SAPI2_ST_TPM2_HMAC_CMD_PARAMS, &TPM2_SHADOW_TPM2_HMAC_CMD_PARAMS},
    {SAPI2_ST_TPM2_HMAC_RSP_PARAMS, &TPM2_SHADOW_TPM2_HMAC_RSP_PARAMS},
    {SAPI2_ST_END, NULL},
};

static const tpm2_shadow_struct*
SAP2_SERIALIZE_lookup_shadow(SAPI2_SERIALIZE_TYPE type)
{
    SAPI2_SERIALIZE_TYPE i = 0;

    for (i = 0; i < (sizeof(type_map) / sizeof(type_map[0])); i++)
    {
        if (type_map[i].type == type)
            return type_map[i].root;
    }
    return NULL;
}

MSTATUS SAPI2_SERIALIZE_serialize(
        SAPI2_SERIALIZE_TYPE type,
        TAP_SERIALIZE_DIRECTION direction,
        ubyte *pIn,
        ubyte4 InSize,
        ubyte *pOut,
        ubyte4 OutSize,
        ubyte4 *pOffset
)
{
    MSTATUS status = ERR_GENERAL;
    const tpm2_shadow_struct *pRoot = NULL;

    pRoot = SAP2_SERIALIZE_lookup_shadow(type);
    if (NULL == pRoot)
    {
        status = ERR_INTERNAL_ERROR;
        goto exit;
    }

    status = TAP_SERIALIZE_serialize(pRoot, direction, pIn, InSize,
            pOut, OutSize, pOffset);
exit:
    return status;
}
#endif  /* (defined(__ENABLE_DIGICERT_TPM2__)) */
