if("${CMAKE_SYSTEM_NAME}" STREQUAL "")
  set(CMAKE_SYSTEM_NAME Linux)
endif()
set(CMAKE_SYSTEM_PROCESSOR ARMv8)

if(MINGW OR CYGWIN OR WIN32)
    set(UTIL_SEARCH_CMD where)
elseif(UNIX OR APPLE)
    set(UTIL_SEARCH_CMD which)
endif()
if (DEFINED ENV{CM_BIN_SYSROOT})
    set(BIN_SYSROOT $ENV{CM_BIN_SYSROOT})
    set(TOOLCHAIN_PREFIX aarch64-poky-linux-)
    set(CMAKE_SYSROOT ${BIN_SYSROOT})
    LIST(APPEND CMAKE_PROGRAM_PATH "${BIN_SYSROOT}/usr/bin")
    LIST(APPEND CMAKE_PROGRAM_PATH "${BIN_SYSROOT}/usr/sbin")
    LIST(APPEND CMAKE_PROGRAM_PATH "${BIN_SYSROOT}/bin")
    LIST(APPEND CMAKE_PROGRAM_PATH "${BIN_SYSROOT}/sbin")
else()
    set(BIN_SYSROOT /home/yocto/sdk/sysroots/)
    set(TOOLCHAIN_PREFIX aarch64-poky-linux-)
    set(CMAKE_SYSROOT ${BIN_SYSROOT}/aarch64-poky-linux)
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/usr/bin")
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/usr/sbin")
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/bin")
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/sbin")
    #LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin")
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux")
    LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux-musl")
endif()

set(ENV{LDFLAGS} "--sysroot=${CMAKE_SYSROOT}")
include_directories(BEFORE SYSTEM ${CMAKE_SYSROOT}/usr/include)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")
