if("${CMAKE_SYSTEM_NAME}" STREQUAL "")
  set(CMAKE_SYSTEM_NAME Linux)
endif()
set(CMAKE_SYSTEM_PROCESSOR ARM-OEML)

if(MINGW OR CYGWIN OR WIN32)
    set(UTIL_SEARCH_CMD where)
elseif(UNIX OR APPLE)
    set(UTIL_SEARCH_CMD which)
endif()
set(BIN_SYSROOT /opt/sysroots/master/yocto_tools/3.1.2/2021.207/arm/sysroots)
set(TOOLCHAIN_PREFIX arm-oemllib32-linux-gnueabi-)
set(CMAKE_SYSROOT ${BIN_SYSROOT}/aarch64-oe-linux)
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/usr/bin")
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/usr/sbin")
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/bin")
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/sbin")
#LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/usr/bin/../x86_64-oesdk-linux/bin")
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/usr/bin/arm-oemllib32-linux-gnueabi")
LIST(APPEND CMAKE_PROGRAM_PATH  "${BIN_SYSROOT}/x86_64-oesdk-linux/usr/bin/arm-oemllib32-linux-musl")

set(ENV{LDFLAGS} "--sysroot=${CMAKE_SYSROOT}")
set(ENV{CFLAGS} "-mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a53 --sysroot=${CMAKE_SYSROOT}")
set(ENV{CXXFLAGS} "-mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a53 --sysroot=${CMAKE_SYSROOT}")
include_directories(BEFORE SYSTEM ${CMAKE_SYSROOT}/usr/include)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")
