# Set default ESP32 version if not provided
if(NOT DEFINED ESP32_VERSION)
    set(ESP32_VERSION "4.3.1")
endif()

# Validate ESP32 version
if("${ESP32_VERSION}" STREQUAL "4.3.1" OR
   "${ESP32_VERSION}" STREQUAL "4.4.1")
    message("Building for ESP32 version ${ESP32_VERSION}")
else()
    message(FATAL_ERROR "ESP version ${ESP32_VERSION} not supported")
endif()

if(NOT DEFINED ESP32_IDF_PATH)
    message(FATAL_ERROR "ESP32_IDF_PATH not set")
endif()
if(NOT DEFINED ESP32_SDKCONFIG_PATH)
    message(FATAL_ERROR "ESP32_SDKCONFIG_PATH not set")
endif()

set(CMAKE_SYSTEM_PROCESSOR "x86")

if("${ESP32_VERSION}" STREQUAL "4.3.1")
    include_directories(${ESP32_IDF_PATH}/components/newlib/platform_include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/port/xtensa/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/port/esp32/.)
    include_directories(${ESP32_IDF_PATH}/components/heap/include)
    include_directories(${ESP32_IDF_PATH}/components/log/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/include/apps)
    include_directories(${ESP32_IDF_PATH}/components/lwip/include/apps/sntp)
    include_directories(${ESP32_IDF_PATH}/components/lwip/lwip/src/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/port/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/port/esp32/include/arch)
    include_directories(${ESP32_IDF_PATH}/components/soc/include)
    include_directories(${ESP32_IDF_PATH}/components/soc/esp32/.)
    include_directories(${ESP32_IDF_PATH}/components/soc/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/hal/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/hal/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_rom/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_rom/esp32)
    include_directories(${ESP32_IDF_PATH}/components/esp_common/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_system/include)
    include_directories(${ESP32_IDF_PATH}/components/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/driver/include)
    include_directories(${ESP32_IDF_PATH}/components/driver/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_ringbuf/include)
    include_directories(${ESP32_IDF_PATH}/components/efuse/include)
    include_directories(${ESP32_IDF_PATH}/components/efuse/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/xtensa/include)
    include_directories(${ESP32_IDF_PATH}/components/xtensa/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/espcoredump/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_timer/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_ipc/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_pm/include)
    include_directories(${ESP32_IDF_PATH}/components/vfs/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_wifi/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_wifi/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_event/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_netif/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_eth/include)
    include_directories(${ESP32_IDF_PATH}/components/tcpip_adapter/include)
    include_directories(${ESP32_IDF_PATH}/components/app_trace/include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include/freertos)
elseif("${ESP32_VERSION}" STREQUAL "4.4.1")
    include_directories(${ESP32_IDF_PATH}/components/newlib/platform_include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include/esp_additions/freertos)
    include_directories(${ESP32_IDF_PATH}/components/freertos/port/xtensa/include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include/esp_additions)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/include/soc)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/include/soc/esp32)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/port/esp32/.)
    include_directories(${ESP32_IDF_PATH}/components/esp_hw_support/port/esp32/private_include)
    include_directories(${ESP32_IDF_PATH}/components/heap/include)
    include_directories(${ESP32_IDF_PATH}/components/log/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/include/apps)
    include_directories(${ESP32_IDF_PATH}/components/lwip/include/apps/sntp)
    include_directories(${ESP32_IDF_PATH}/components/lwip/lwip/src/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/port/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/lwip/port/esp32/include/arch)
    include_directories(${ESP32_IDF_PATH}/components/soc/include)
    include_directories(${ESP32_IDF_PATH}/components/soc/esp32/.)
    include_directories(${ESP32_IDF_PATH}/components/soc/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/hal/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/hal/include)
    include_directories(${ESP32_IDF_PATH}/components/hal/platform_port/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_rom/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_rom/include/esp32)
    include_directories(${ESP32_IDF_PATH}/components/esp_rom/esp32)
    include_directories(${ESP32_IDF_PATH}/components/esp_common/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_system/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_system/port/soc)
    include_directories(${ESP32_IDF_PATH}/components/esp_system/port/public_compat)
    include_directories(${ESP32_IDF_PATH}/components/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/xtensa/include)
    include_directories(${ESP32_IDF_PATH}/components/xtensa/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/driver/include)
    include_directories(${ESP32_IDF_PATH}/components/driver/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_pm/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_ringbuf/include)
    include_directories(${ESP32_IDF_PATH}/components/efuse/include)
    include_directories(${ESP32_IDF_PATH}/components/efuse/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/vfs/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_wifi/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_event/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_netif/include)
    include_directories(${ESP32_IDF_PATH}/components/tcpip_adapter/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_phy/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_phy/esp32/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_ipc/include)
    include_directories(${ESP32_IDF_PATH}/components/app_trace/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_timer/include)
    include_directories(${ESP32_IDF_PATH}/components/mbedtls/port/include)
    include_directories(${ESP32_IDF_PATH}/components/mbedtls/mbedtls/include)
    include_directories(${ESP32_IDF_PATH}/components/mbedtls/esp_crt_bundle/include)
    include_directories(${ESP32_IDF_PATH}/components/app_update/include)
    include_directories(${ESP32_IDF_PATH}/components/spi_flash/include)
    include_directories(${ESP32_IDF_PATH}/components/bootloader_support/include)
    include_directories(${ESP32_IDF_PATH}/components/nvs_flash/include)
    include_directories(${ESP32_IDF_PATH}/components/pthread/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_gdbstub/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_gdbstub/xtensa)
    include_directories(${ESP32_IDF_PATH}/components/esp_gdbstub/esp32)
    include_directories(${ESP32_IDF_PATH}/components/espcoredump/include)
    include_directories(${ESP32_IDF_PATH}/components/espcoredump/include/port/xtensa)
    include_directories(${ESP32_IDF_PATH}/components/wpa_supplicant/include)
    include_directories(${ESP32_IDF_PATH}/components/wpa_supplicant/port/include)
    include_directories(${ESP32_IDF_PATH}/components/wpa_supplicant/esp_supplicant/include)
    include_directories(${ESP32_IDF_PATH}/components/ieee802154/include)
    include_directories(${ESP32_IDF_PATH}/components/console)
    include_directories(${ESP32_IDF_PATH}/components/asio/asio/asio/include)
    include_directories(${ESP32_IDF_PATH}/components/asio/port/include)
    include_directories(${ESP32_IDF_PATH}/components/cbor/port/include)
    include_directories(${ESP32_IDF_PATH}/components/unity/include)
    include_directories(${ESP32_IDF_PATH}/components/unity/unity/src)
    include_directories(${ESP32_IDF_PATH}/components/cmock/CMock/src)
    include_directories(${ESP32_IDF_PATH}/components/coap/port/include)
    include_directories(${ESP32_IDF_PATH}/components/coap/libcoap/include)
    include_directories(${ESP32_IDF_PATH}/components/nghttp/port/include)
    include_directories(${ESP32_IDF_PATH}/components/nghttp/nghttp2/lib/includes)
    include_directories(${ESP32_IDF_PATH}/components/esp-tls)
    include_directories(${ESP32_IDF_PATH}/components/esp-tls/esp-tls-crypto)
    include_directories(${ESP32_IDF_PATH}/components/esp_adc_cal/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_hid/include)
    include_directories(${ESP32_IDF_PATH}/components/tcp_transport/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_http_client/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_http_server/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_https_ota/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_lcd/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_lcd/interface)
    include_directories(${ESP32_IDF_PATH}/components/protobuf-c/protobuf-c)
    include_directories(${ESP32_IDF_PATH}/components/protocomm/include/common)
    include_directories(${ESP32_IDF_PATH}/components/protocomm/include/security)
    include_directories(${ESP32_IDF_PATH}/components/protocomm/include/transports)
    include_directories(${ESP32_IDF_PATH}/components/mdns/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_local_ctrl/include)
    include_directories(${ESP32_IDF_PATH}/components/sdmmc/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_serial_slave_link/include)
    include_directories(${ESP32_IDF_PATH}/components/esp_websocket_client/include)
    include_directories(${ESP32_IDF_PATH}/components/expat/expat/expat/lib)
    include_directories(${ESP32_IDF_PATH}/components/expat/port/include)
    include_directories(${ESP32_IDF_PATH}/components/wear_levelling/include)
    include_directories(${ESP32_IDF_PATH}/components/fatfs/diskio)
    include_directories(${ESP32_IDF_PATH}/components/fatfs/vfs)
    include_directories(${ESP32_IDF_PATH}/components/fatfs/src)
    include_directories(${ESP32_IDF_PATH}/components/freemodbus/common/include)
    include_directories(${ESP32_IDF_PATH}/components/idf_test/include)
    include_directories(${ESP32_IDF_PATH}/components/idf_test/include/esp32)
    include_directories(${ESP32_IDF_PATH}/components/jsmn/include)
    include_directories(${ESP32_IDF_PATH}/components/json/cJSON)
    include_directories(${ESP32_IDF_PATH}/components/libsodium/libsodium/src/libsodium/include)
    include_directories(${ESP32_IDF_PATH}/components/libsodium/port_include)
    include_directories(${ESP32_IDF_PATH}/components/mqtt/esp-mqtt/include)
    include_directories(${ESP32_IDF_PATH}/components/openssl/include)
    include_directories(${ESP32_IDF_PATH}/components/perfmon/include)
    include_directories(${ESP32_IDF_PATH}/components/spiffs/include)
    include_directories(${ESP32_IDF_PATH}/components/ulp/include)
    include_directories(${ESP32_IDF_PATH}/components/wifi_provisioning/include)
    include_directories(${ESP32_IDF_PATH}/components/freertos/include/freertos)
endif()
include_directories(${ESP32_SDKCONFIG_PATH})

include(${ESP32_IDF_PATH}/tools/cmake/toolchain-esp32.cmake)