##Subject
countryName=US
commonName=device-signing
stateOrProvinceName=California
localityName=Sunnyvale
organizationName=DBA
organizationalUnitName=BU
##Requested Extensions
hasBasicConstraints=true
isCA=false
certPathLen=-1
keyUsage=digitalSignature
