# Set the name of target binary
#CONFIG_KERNEL_BIN_NAME="trustedge"
#CONFIG_DEBUG=y
#CONFIG_SIZE_OPTIMIZATIONS_AGGRESSIVE=y

# the number of bytes in the arena for C library malloc
#CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=102000

CONFIG_HEAP_MEM_POOL_SIZE=17000
CONFIG_DYNAMIC_THREAD_STACK_SIZE=14000
CONFIG_MAIN_STACK_SIZE=50000

#CONFIG_ZTEST_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096
CONFIG_SHELL_STACK_SIZE=4096

CONFIG_LOG_BACKEND_FS=y
CONFIG_LOG_BACKEND_FS_FILE_SIZE=1024000
CONFIG_LOG_BACKEND_FS_FILES_LIMIT=5
CONFIG_LOG_BACKEND_FS_DIR="/lfs1/log"

CONFIG_PRINTK=y
CONFIG_LOG_CMDS=y
CONFIG_INIT_STACKS=y
CONFIG_KERNEL_SHELL=y
CONFIG_THREAD_MONITOR=y
CONFIG_BOOT_BANNER=n
CONFIG_THREAD_NAME=y
CONFIG_DEVICE_SHELL=y
CONFIG_DATE_SHELL=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_STATS=y
CONFIG_STATS_SHELL=y

#CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.142"
#CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.168.1.124"
#CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.1.1"
#CONFIG_REQUIRES_FULL_LIBC=y

# number of bytes for k_malloc

#CONFIG_POSIX_API=y

# for enabling poxis threads
#CONFIG_POSIX_THREADS=y # pthread
#CONFIG_POSIX_TIMERS=y
#CONFIG_THREAD_STACK_INFO=y
#CONFIG_DYNAMIC_THREAD=y

#CONFIG_DYNAMIC_THREAD_POOL_SIZE=20
#CONFIG_POSIX_THREAD_KEYS_MAX=20
#CONFIG_POSIX_THREAD_THREADS_MAX=20
#CONFIG_MAX_PTHREAD_MUTEX_COUNT=20
#CONFIG_MAX_PTHREAD_COND_COUNT=20

# Enable thread awareness for debugging tools supporting it
#CONFIG_DEBUG_THREAD_INFO=y

#CONFIG_LOG=y

#CONFIG_SHELL=y
#CONFIG_SHELL_LOG_LEVEL_INF=y

#CONFIG_FILE_SYSTEM=y
#CONFIG_FILE_SYSTEM_SHELL=y

#CONFIG_FILE_SYSTEM_LITTLEFS=y
#CONFIG_FLASH_MAP=y
#CONFIG_FLASH=y

# Networking config
#CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=n
#CONFIG_NET_SOCKETS=y
#CONFIG_NETWORKING=y
#CONFIG_NET_IPV4=y
#CONFIG_NET_DHCPV4=y
#CONFIG_NET_IPV6=n
#CONFIG_NET_IF_MAX_IPV4_COUNT=2
#CONFIG_NET_TCP=y
#CONFIG_NET_LOG=y

#CONFIG_NET_SHELL=y

#CONFIG_NET_CONFIG_SETTINGS=y
#CONFIG_NET_CONFIG_NEED_IPV4=y

#CONFIG_NET_MAX_CONN=10

#CONFIG_ZVFS_POLL_MAX=10
#CONFIG_ZVFS_OPEN_MAX=10
# Enable the DNS resolver
#CONFIG_DNS_RESOLVER=y
# Enable additional buffers
#CONFIG_DNS_RESOLVER_ADDITIONAL_BUF_CTR=5
# Enable additional queries
#CONFIG_DNS_RESOLVER_ADDITIONAL_QUERIES=2
# Enable mDNS support
#CONFIG_MDNS_RESOLVER=y
# Enable LLMNR support
#CONFIG_LLMNR_RESOLVER=n

#CONFIG_DNS_RESOLVER_MAX_SERVERS=2
#CONFIG_DNS_SERVER_IP_ADDRESSES=y
#CONFIG_DNS_NUM_CONCUR_QUERIES=5

#CONFIG_DNS_SERVER1="8.8.8.8:53"
#CONFIG_DNS_SERVER2="1.1.1.1:53"

#CONFIG_NET_PKT_RX_COUNT=12
#CONFIG_NET_PKT_TX_COUNT=12
#CONFIG_NET_BUF_RX_COUNT=64
#CONFIG_NET_BUF_TX_COUNT=64

#CONFIG_NET_TCP_LOG_LEVEL_DBG=n

#CONFIG_HWINFO=y


# Set current time from ntp server
#CONFIG_SNTP=y
#CONFIG_SNTP_LOG_LEVEL_DBG=n
#CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
#CONFIG_NET_CONFIG_SNTP_INIT_RESYNC=y
#CONFIG_NET_CONFIG_SNTP_INIT_SERVER="north-america.pool.ntp.org"