# Define the version string
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")

if(DEFINED ENV{VERSION_MAJOR})
  set(CPACK_PACKAGE_VERSION_MAJOR "$ENV{VERSION_MAJOR}")
endif()

if(DEFINED ENV{VERSION_MINOR})
  set(CPACK_PACKAGE_VERSION_MINOR "$ENV{VERSION_MINOR}")
endif()

if(DEFINED ENV{VERSION_PATCH})
  set(CPACK_PACKAGE_VERSION_PATCH "$ENV{VERSION_PATCH}")
endif()

set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
