/*
 * build_info.h — stub for ThreadX/STM32 build
 *
 * TrustEdge source files include this header for build-metadata macros.
 * On embedded targets the macros are either unused or replaced by empty
 * definitions so the SDK compiles without a dedicated build system.
 */

#ifndef __BUILD_INFO_HEADER__
#define __BUILD_INFO_HEADER__

#define TRUSTEDGE_BUILD_VERSION     "embedded"
#define TRUSTEDGE_BUILD_DATE        "unknown"
#define TRUSTEDGE_BUILD_COMMIT      "unknown"
#define TRUSTEDGE_BUILD_BRANCH      "unknown"

/* BUILD_INFO_VERSION_VAL: consumed directly by trustedge_agent_main.c and
 * trustedge_agent_attributes.c — must be a string literal expression.     */
#define BUILD_INFO_VERSION_VAL      TRUSTEDGE_BUILD_VERSION

#if defined(__ENABLE_DIGICERT_BUILD_INFO__)
/* build_info.c defines a real BUILD_INFO_print(); supply the _VAL macros it
 * requires (normally generated by CMake from build_info.h.in) instead of
 * redefining BUILD_INFO_print() itself, which would break its compilation. */
#define BUILD_INFO_YEAR_VAL         "2026"
#define BUILD_INFO_PLATFORM_VAL     "embedded"
#define BUILD_INFO_BUILD_VAL        TRUSTEDGE_BUILD_COMMIT
#define BUILD_INFO_TYPE_VAL         "embedded"
#define BUILD_INFO_DATE_VAL         TRUSTEDGE_BUILD_DATE
MOC_EXTERN void BUILD_INFO_print(void);
#else
/* BUILD_INFO_print: no-op — build_info.c is not compiled in for this target. */
#define BUILD_INFO_print()          ((void)0)
#endif

/* pthread_join prototype for ThreadX/AzureRTOS targets.
 * Linux and FreeRTOS-ESP32 get it from their own <pthread.h> include.
 * Implementation: the stub in syscalls.c (body is unreachable at runtime
 * because the device is PROVISIONED, never PREINSTALL).                   */
#if !defined(__RTOS_LINUX__) && !(defined(__RTOS_FREERTOS__) && defined(__RTOS_FREERTOS_ESP32__))
int pthread_join(unsigned long thread, void **retval);
#endif

#endif /* __BUILD_INFO_HEADER__ */
