name: "NanoMQTT Integration Tests"

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 3 * * 5'   # Friday 9am IST (3:30 UTC)

jobs:
  mqtt-integration-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake
        cmake --version
        sudo apt-get install -y python3-pip
        pip3 install paho-mqtt
        pip3 install psutil
        sudo apt-get install -y lcov
        lcov --version
 
    - name: Create /etc/digicert/keystore/ca folder 
      run: |
        sudo mkdir -p /etc/digicert/keystore/ca
        sudo chown -R $(whoami):$(whoami) /etc/digicert

    - name: Clone mocn-qa-m-products
      env:
        MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
      run: |
        git clone https://${MY_SECRET_TOKEN}@github.com/digicert/mocn-qa-m-products.git

    - name: Copy MQTT Test Files
      run: |
        cp -r mocn-qa-m-products/mqttc_test/test_open_source/* .

    - name: Make run_nanomqtt_client.sh executable
      run: chmod +x run_nanomqtt_client.sh

    - name: Run MQTT Integration Test
      env:
        CM_ENV_CODE_COVERAGE: 1
      run: |
        ./run_nanomqtt_client.sh

    - name: Baseline Coverage
      run: |
        lcov --no-external --capture --initial --directory . --output-file /tmp/mqtt_base.info

    - name: Capture Coverage
      run: |
        lcov --no-external --capture --directory . --output-file /tmp/mqtt_test.info
        lcov --add-tracefile /tmp/mqtt_base.info --add-tracefile /tmp/mqtt_test.info --output-file /tmp/mqtt_total.info

    - name: Print Coverage Summary
      run: |
        echo "Coverage Summary:"
        lcov --extract /tmp/mqtt_total.info '*/mqtt/*' --output-file /tmp/mqtt_filtered.info
        lcov --list /tmp/mqtt_filtered.info | tee coverage_summary.log

    - name: Upload Coverage Summary
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: nanomqtt_integration_test_coverage_summary
        path: coverage_summary.log

    - name: Cleanup mocn-qa-m-products
      if: always()
      run: |
        rm -rf mocn-qa-m-products
