name: "NanoSSH Integration Tests"
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 3 * * 1'   # Monday 9am IST
    - cron: '30 3 * * 4'   # Thursday 9am IST

jobs:
  ssh-integration-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake python3-pip valgrind expect
        cmake --version
        pip3 install --upgrade pip
        pip3 install psutil
        valgrind --version
        expect -v
        sudo apt-get install -y lcov
        lcov --version

    - name: Clone mocn-qa-m-products
      env:
        MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
      run: |
        git clone https://${MY_SECRET_TOKEN}@github.com/digicert/mocn-qa-m-products.git

    - name: Copy SSH Test Files
      run: |
        cp -r mocn-qa-m-products/ssh_test/test_open_source/* .
        cp -r mocn-qa-m-products/ssl_test/keystore .

    - name: Prepare SSHD
      run: |
        sudo mkdir -p /run/sshd
        sudo chmod 0755 /run/sshd

    - name: Setup jenkins_agent user and authorized_keys
      run: |
        # Variables
        USERNAME="jenkins_agent"
        PASSWORD="${{ secrets.JENKINS_AGENT_PASSWORD }}"
        AUTH_KEYS_SRC="mocn-qa-m-products/ssh_test/test_open_source/openssh_keys/authorized_keys"
        USER_HOME="/home/$USERNAME"

        # 1. Create the user with password
        sudo useradd -m -s /bin/bash $USERNAME
        echo "$USERNAME:$PASSWORD" | sudo chpasswd
        sudo usermod -aG sudo $USERNAME

        # 2. Setup .ssh folder
        sudo mkdir -p $USER_HOME/.ssh
        sudo chown $USERNAME:$USERNAME $USER_HOME/.ssh
        sudo chmod 700 $USER_HOME/.ssh

        # 3. Copy authorized_keys
        sudo cp $AUTH_KEYS_SRC $USER_HOME/.ssh/authorized_keys
        sudo chown $USERNAME:$USERNAME $USER_HOME/.ssh/authorized_keys
        sudo chmod 600 $USER_HOME/.ssh/authorized_keys

    - name: Run SSH Integration Test
      env:
        CM_ENV_CODE_COVERAGE: 1
      run: |
        PYTHONUNBUFFERED=1 python3 run.py global_nanossh_cap_no_tap.json

    - name: Baseline Coverage
      run: |
        lcov --no-external --capture --initial --directory . --output-file /tmp/ssh_base.info

    - name: Capture Coverage
      run: |
        lcov --no-external --capture --directory . --output-file /tmp/ssh_test.info
        lcov --add-tracefile /tmp/ssh_base.info --add-tracefile /tmp/ssh_test.info --output-file /tmp/ssh_total.info

    - name: Print Coverage Summary
      run: |
        echo "Coverage Summary:"
        lcov --extract /tmp/ssh_total.info '*/ssh/*' --output-file /tmp/ssh_filtered.info
        lcov --list /tmp/ssh_filtered.info | tee coverage_summary.log

    - name: Upload Coverage Summary Artifact
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: coverage_summary
        path: coverage_summary.log
        retention-days: 5
    - name: Upload Valgrind Report Artifact
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: report_valgrind
        path: report_valgrind.zip
        retention-days: 5

    - name: Cleanup mocn-qa-m-products
      if: always()
      run: |
        rm -rf mocn-qa-m-products
