name: TrustEdge Sanity Tests
on: 
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 15 * * *'
  push:
    paths:
      - .github/workflows/trustedge_sanity_tests.yml

permissions:
  contents: read

env:
  NEXUS_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/trustedge/dev/nux64/
  NEXUS_REPO_RPI_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/trustedge/dev/rpi64/
  NEXUS_REPO_RPI32_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/trustedge/dev/rpi32/
  NEXUS_CMAKE_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/cmake/cmake-3.22.1/cmake-3.22.1-linux-x86_64.sh
  NEXUS_NINJA_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/ninja/ninja-build-1.10.1/ninja-build_1.10.1-1_amd64.deb
  NEXUS_LINARO_AARCH64_SYSROOT_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/linaro/linaro-6.5.0-2018-12/sysroot-glibc-linaro-2.23-2018.12-aarch64-linux-gnu.tar.xz
  NEXUS_LINARO_AARCH64_GCC_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/linaro/linaro-6.5.0-2018-12/gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu.tar.xz
  NEXUS_LINARO_ARM_SYSROOT_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/linaro/linaro-6.5.0-2018-12/sysroot-glibc-linaro-2.23-2018.12-arm-linux-gnueabihf.tar.xz
  NEXUS_LINARO_ARM_GCC_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/linaro/linaro-6.5.0-2018-12/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
jobs:
  Trustedge_Sanity_Test:
    runs-on: ${{ github.repository == 'digicert/trustcore-test' && 'digicert-large' || 'ubuntu-22.04' }}
    env:
      PLATFORMS_TO_TEST: ${{ github.repository == 'digicert/trustcore-test' && 'x64 rpi64 rpi32' || 'x64' }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Generate TrustEdge version number
        id: trustedge-client-version
        uses: paulhatch/semantic-version@a8f8f59fd7f0625188492e945240f12d7ad2dca3
        with:
          version_format: "${major}.${minor}.${patch}-${increment}"
          tag_prefix: "trustedge_"
          branch: main
          search_commit_body: true

      - name: Install dependencies from Nexus
        if: github.repository == 'digicert/trustcore-test'
        run: |
          curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_CMAKE_REPO_URL }} -O
          export CMAKE_DIR=/opt/cmake
          sudo mkdir $CMAKE_DIR
          sudo bash cmake-3.22.1-linux-x86_64.sh --skip-license --prefix=$CMAKE_DIR
          export CMAKE_DIR=/opt/cmake
          export PATH=$CMAKE_DIR/bin:$PATH
          cmake --version
          curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_NINJA_REPO_URL }} -O
          sudo dpkg -i ninja-build_1.10.1-1_amd64.deb
          ninja --version
          sudo apt update
          sudo apt install -y rpm

      - name: Install dependencies from public repositories
        if: github.repository != 'digicert/trustcore-test'
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full cproto cmake ninja-build rpm
          python3 -m pip install --upgrade jenkinsapi
          cmake --version
          ninja --version

      - name: Docker Setup
        run: |
          sudo docker build -t trustedge-test -f src/trustedge/sanity_test/Dockerfile .
          sudo docker run --privileged --name trustedge-sanity -d -v /sys/fs/cgroup:/sys/fs/cgroup:rw -p 2222:22 --tmpfs /run --tmpfs /run/lock -e container=docker --cap-add SYS_ADMIN --stop-signal SIGRTMIN+3 --cgroupns=host trustedge-test /lib/systemd/systemd
          sleep 5

      - name: Build and Verify All Platforms
        run: |
          export CMAKE_DIR=/opt/cmake
          export PATH=$CMAKE_DIR/bin:$PATH

          for platform in $PLATFORMS_TO_TEST; do
            echo ">>> Building TrustEdge for $platform"
          
            if [ "$platform" == "x64" ]; then
              ./scripts/ci/trustedge/ci_trustedge_build.sh --version-string ${{ steps.trustedge-client-version.outputs.version }} --monolithic --package --tpm2 --cvc --proxy --pqc --pqc-composite --enable-pc
              
            elif [ "$platform" == "rpi64" ]; then
              sudo mkdir -p /opt/sysroots/master
              curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_LINARO_AARCH64_SYSROOT_REPO_URL }} -O
              sudo tar -xf sysroot-glibc-linaro-2.23-2018.12-aarch64-linux-gnu.tar.xz -C /opt/sysroots/master
              curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_LINARO_AARCH64_GCC_REPO_URL }} -O
              sudo tar -xf gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu.tar.xz -C /opt/sysroots/master
              ./scripts/ci/trustedge/ci_trustedge_build.sh --version-string ${{ steps.trustedge-client-version.outputs.version }} --toolchain rpi64 --monolithic --package --tpm2 --cvc --proxy --pqc --pqc-composite --enable-pc
            
            elif [ "$platform" == "rpi32" ]; then
              sudo mkdir -p /opt/sysroots/master
              curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_LINARO_ARM_SYSROOT_REPO_URL }} -O
              sudo tar -xf sysroot-glibc-linaro-2.23-2018.12-arm-linux-gnueabihf.tar.xz -C /opt/sysroots/master
              curl --fail --silent --show-error --location -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_LINARO_ARM_GCC_REPO_URL }} -O
              sudo tar -xf gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/sysroots/master
              ./scripts/ci/trustedge/ci_trustedge_build.sh --version-string ${{ steps.trustedge-client-version.outputs.version }} --toolchain rpi32 --monolithic --package --tpm2 --cvc --proxy --pqc --pqc-composite --enable-pc
            fi

            echo ">>> Verifying build output for $platform"
            sudo docker exec trustedge-sanity mkdir -p /tmp/deb/$platform /tmp/tgz/$platform
            missing_files=false
            if ls dist/trustedge*.deb 1> /dev/null 2>&1; then
              sudo docker cp dist/trustedge*.deb trustedge-sanity:/tmp/deb/$platform
            else
              echo "[Test Failed] No TrustEdge .deb file found for $platform"
              missing_files=true
            fi

            if ls dist/trustedge*.tar.gz 1> /dev/null 2>&1; then
              sudo docker cp dist/trustedge*.tar.gz trustedge-sanity:/tmp/tgz/$platform
            else
              echo "[Test Failed] No TrustEdge .tar.gz file found for $platform"
              missing_files=true
            fi

            if [ "$missing_files" = true ]; then
              echo "[Test Failed] TrustEdge build for $platform failed"
              exit 1
            fi
            echo "[Test Passed] TrustEdge build for $platform succeeded"
          done

      - name: Run Trustedge Sanity Test Script
        run: |
          echo ">>> Running sanity test script"
          sudo docker cp src/trustedge/sanity_test/register_device.py trustedge-sanity:/tmp
          sudo docker cp src/trustedge/sanity_test/disable_delete_device.py trustedge-sanity:/tmp
          sudo docker cp scripts/ci/trustedge/trustedge_sanity_test.sh trustedge-sanity:/tmp
          sudo docker exec -e DEMO_API_KEY=${{ secrets.DEMO_API_KEY }} -e PLATFORMS_TO_TEST="$PLATFORMS_TO_TEST" trustedge-sanity /tmp/trustedge_sanity_test.sh
          
      - name: Get Slack User ID
        if: always()
        id: slack_map
        run: |
          GITHUB_USER="${{ github.actor }}"
          SLACK_USER_MAP='${{ vars.SLACK_USER_MAP_JSON }}'
          
          SLACK_USER_ID=$(echo "$SLACK_USER_MAP" | jq -r --arg user "$GITHUB_USER" '.[$user] // ""')
          
          echo "GitHub User: $GITHUB_USER"
          echo "slack_user_id=$SLACK_USER_ID" >> $GITHUB_OUTPUT

      - name: Send Slack notification (Failure)
        if: always() && (failure() || cancelled()) 
        run: |
          SLACK_USER_ID="${{ steps.slack_map.outputs.slack_user_id }}"
          if [ -n "$SLACK_USER_ID" ]; then
            MENTION="<@$SLACK_USER_ID>"
          else
            MENTION="${GITHUB_ACTOR}"
          fi
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            MESSAGE="TrustEdge Sanity Test failed on branch \`${GITHUB_REF_NAME}\`\nRun: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          else
            MESSAGE="TrustEdge Sanity Test failed on branch \`${GITHUB_REF_NAME}\`\nTriggered by: ${MENTION}\nRun: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          fi  
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"${MESSAGE}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
        
