name: TrustEdge Arago ToolChain 

permissions:
  contents: read

on:
  workflow_dispatch: {} 

env:
  NEXUS_CMAKE_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/cmake/cmake-3.22.1/cmake-3.22.1-linux-x86_64.sh
  NEXUS_NINJA_REPO_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/ninja/ninja-build-1.10.1/ninja-build_1.10.1-1_amd64.deb
  NEXUS_ARAGO_TOOLCHAIN_URL: https://repo.dev.blu.digicert.com/repository/digicert-artifacts/dependencies/arago/arago-2021.09-toolchain-2021.09.sh

jobs:
  trustedge-arago-toolchainbuild:
    runs-on: [digicert-large]
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          curl -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_CMAKE_REPO_URL }} -O
          export CMAKE_DIR=/opt/cmake
          sudo mkdir $CMAKE_DIR
          sudo bash cmake-3.22.1-linux-x86_64.sh --skip-license --prefix=$CMAKE_DIR
          export CMAKE_DIR=/opt/cmake
          export PATH=$CMAKE_DIR/bin:$PATH
          cmake --version
          curl -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} ${{ env.NEXUS_NINJA_REPO_URL }} -O -v
          sudo dpkg -i ninja-build_1.10.1-1_amd64.deb
          ninja --version

      - name: Install RPM tools
        run: |
          sudo apt update
          sudo apt install -y rpm

      - name: Download Arago Toolchain
        run: |
          curl -v -u ${{ secrets.DEV_REPO_USERNAME }}:${{ secrets.DEV_REPO_PASSWORD }} -O "${{ env.NEXUS_ARAGO_TOOLCHAIN_URL }}"

      - name: Install Arago Toolchain
        run: |
          chmod +x arago-2021.09-toolchain-2021.09.sh
          sudo ./arago-2021.09-toolchain-2021.09.sh -y

      - name: Build TrustEdge for arago toolchain
        run: |
          source /usr/local/arago-x86_64/environment-setup-aarch64-oe-linux
          ./scripts/ci/trustedge/ci_trustedge_build.sh --monolithic --cvc --proxy --pqc --pqc-composite --enable-pc --toolchain arago_linux_aarch64 --package --tee --tee-path /usr/local/arago-x86_64/sysroots/aarch64-oe-linux/usr/lib/

      - name: Upload TGZ Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: trustedge-arago-x86_64-tgz
          path: dist/*.tar.gz
